; This file was automatically generated by SIDdecompiler 0.8 from 'SID/Stinsens_Last_Night_of_89.sid'
; Name:      Stinsen's Last Night of '89
; Author:    Thomas E. Petersen (Laxity)
; Released:  2021 Bonzai
; Subtunes:  1

                * = $03e8

init            jmp l1692
                .byte $4c, $9b, $16
play            lda #$00
                bit l1781
                bmi l1051
                bvs l1047
                ldx #$75
l1011           sta l1782,X
                dex 
                bne l1011
                ldx l1782
                lda l17fb,X
                sta l1780
                sta l1784
                lda l17fc,X
                and #$0f
                sta l1785
                lda l17fc,X
                and #$70
                sta l1786
                lda #$02
                sta l1783
                sta l17f8
                sta l17f9
                sta l17fa
                lda #$80
                sta l1781
                rts 
l1047           .byte $8d, $04, $d4, $8d, $0b, $d4, $8d, $12
                .byte $d4, $60
l1051           dec l1783
                bpl l106d
                ldx l1784
                lda l1a19,X
                sta l1783
                inx 
                lda l1a19,X
                cmp #$7f
                bne l106a
                ldx l1780
l106a           stx l1784
l106d           ldx #$02
l106f           lda l17f8,X
                cmp #$01
                bne l10af
                lda l1795,X
                bne l10af
                inc l1795,X
                lda l1a1c,X
                sta $fc
                lda l1a1f,X
                sta $fd
                ldy l1792,X
                lda ($fc),Y
                bpl l1098
                sec 
                sbc #$a0
                sta l17b0,X
                iny 
                lda ($fc),Y
l1098           sta l179b,X
                iny 
                lda ($fc),Y
                cmp #$ff
                bne l10a6
                iny 
                lda ($fc),Y
                tay 
l10a6           tya 
                sta l1792,X
                lda #$00
                sta l1798,X
l10af           lda l1783
                bne l1121
                dec l178f,X
                bpl l1121
                ldy l179b,X
                lda l1a22,Y
                sta $fc
                lda l1a49,Y
                sta $fd
                ldy l1798,X
                lda ($fc),Y
                bpl l10f4
                cmp #$c0
                bcc l10d9
                sta l17aa,X
                iny 
                lda ($fc),Y
                bpl l10f4
l10d9           cmp #$a0
                bcc l10e5
                sta l17a7,X
                iny 
                lda ($fc),Y
                bpl l10f4
l10e5           cmp #$90
                bcc l10ec
                inc l17a1,X
l10ec           and #$0f
                sta l179e,X
                iny 
                lda ($fc),Y
l10f4           sta l17a4,X
                beq l10fd
                cmp #$7e
                bne l1102
l10fd           inc l17a1,X
                bne l1108
l1102           lda l17b0,X
                sta l17b3,X
l1108           iny 
                tya 
                sta l1798,X
                lda l179e,X
                sta l178f,X
                lda #$02
                sta l17f8,X
                lda ($fc),Y
                cmp #$7f
                bne l1121
                dec l1795,X
l1121           ldy l17f8,X
                bmi l115c
                lda l17a1,X
                bne l115c
                cpy #$01
                beq l1152
                cpy #$00
                beq l115f
                lda l17a7,X
                and #$1f
                tay 
                lda l1825,Y
                bpl l114d
                and #$0f
                tay 
                lda l18d8,Y
                sta l17ef,X
                lda l18d9,Y
                sta l17f2,X
l114d           lda #$fe
                sta l17f5,X
l1152           lda l17bc,X
                cmp #$04
                bcs l115c
                jmp l1540
l115c           jmp l1379
l115f           lda #$ff
                sta l17f5,X
                lda l17a7,X
                bpl l119f
                and #$1f
                sta l17ad,X
                sta l17a7,X
                tay 
                lda l17fd,Y
                sta l17d4,X
                sta l17ef,X
                lda l1811,Y
                sta l17d7,X
                sta l17f2,X
                lda l1825,Y
                and #$20
                beq l1193
                lda l178b
                ora l177a,X
                bne l1199
l1193           lda l178b
                and l177d,X
l1199           sta l178b
                jmp l11c8
l119f           ldy l17ad,X
                lda l17d4,X
                sta l17ef,X
                lda l17d7,X
                sta l17f2,X
                lda l17bc,X
                cmp #$03
                beq l11cd
                cmp #$04
                bne l11c8
                lda l17ce,X
                sta l17d1,X
                lda l17cb,X
                sta l17c8,X
                jmp l11cd
l11c8           lda #$00
                sta l17bc,X
l11cd           lda l1825,Y
                and #$10
                lsr 
                ora #$01
                sta l17ec,X
                lda l1825,Y
                and #$40
                beq l11f1
                asl 
                sta l178c
                lda l1839,Y
                sta l178e
                dec l178e
                lda #$00
                sta l178d
l11f1           lda l1861,Y
                sta l17bf,X
                lda l184d,Y
                sta l17c2,X
                lda #$00
                sta l17c5,X
l1202           lda l17aa,X
                bmi l120a
                jmp l131f
l120a           and #$3f
                sta l17aa,X
                tay 
                lda l1875,Y
                and #$0f
                tay 
                lda l1761,Y
                sta l1288+1
                ldy l17aa,X
                jmp l1286
                lda l1896,Y
                sta l17cb,X
                lda l18b7,Y
                sta l17c8,X
                lda #$01
                jmp l131c
                lda l1896,Y
                sta l17cb,X
                lda l18b7,Y
                sta l17c8,X
                lda #$03
                jmp l131c
l1244           lda l1896,Y
                bmi l1278
                sta l17cb,X
                sta l17c8,X
                lda l18b7,Y
                sta l17ce,X
                sta l17d1,X
                lda #$04
                jmp l131c
                .byte $b9, $96, $18, $9d, $cb, $17, $29, $7f
                .byte $9d, $c8, $17, $b9, $b7, $18, $9d, $d1
                .byte $17, $a9, $00, $9d, $ce, $17, $a9, $05
                .byte $4c, $1c, $13
l1278           .byte $4c, $1a, $13, $b9, $b7, $18, $29, $0f
                .byte $8d, $85, $17, $4c, $1f, $13
l1286           sec 
l1288           bcs l1244
                lda l18b7,Y
                and #$0f
                sta l17c8,X
                lda l1896,Y
                clc 
                adc #$01
                sta l17cb,X
                lsr 
                bcc l129f
                ora #$80
l129f           sta l17ce,X
                lda #$02
                sta l17d1,X
                jmp l131c
                lda l1896,Y
                sta l17ef,X
                lda l18b7,Y
                sta l17f2,X
                jmp l131f
                .byte $b9, $96, $18, $9d, $d4, $17, $9d, $ef
                .byte $17, $b9, $b7, $18, $9d, $d7, $17, $9d
                .byte $f2, $17, $4c, $1f, $13
                lda l18b7,Y
                sta l17bf,X
                jmp l131f
                lda #$80
                sta l178c
                lda l18b7,Y
                sta l178e
                dec l178e
                lda #$00
                sta l178d
                jmp l131f
                .byte $b9, $b7, $18, $9d, $c2, $17, $a9, $00
                .byte $9d, $c5, $17, $4c, $1f, $13, $b9, $b7
                .byte $18, $8d, $80, $17, $8d, $84, $17, $a8
                .byte $b9, $1a, $1a, $c9, $7f, $f0, $03, $ee
                .byte $84, $17, $b9, $19, $1a, $a8, $88, $8c
                .byte $83, $17, $4c, $1f, $13, $a9, $00
l131c           sta l17bc,X
l131f           lda l17a1,X
                bne l132a
                lda l17a4,X
                jmp l133e
l132a           lda l17a4,X
                beq l1368
                cmp #$7e
                beq l136c
                tay 
                clc 
                adc l17b3,X
                cmp l17b9,X
                beq l1371
                tya 
l133e           sta l17b6,X
                clc 
                adc l17b3,X
                sta l17b9,X
                tay 
                lda l17bc,X
                cmp #$03
                beq l1360
                cmp #$04
                beq l1360
                lda l1701,Y
                sta l17da,X
                lda l16a1,Y
                sta l17dd,X
l1360           lda l17a1,X
                bne l136c
                jmp l1582
l1368           lda #$fe
                bne l136e
l136c           lda #$ff
l136e           sta l17f5,X
l1371           lda #$00
                sta l17a1,X
                jmp l15e1
l1379           lda l17bc,X
                tay 
                lda l1771,Y
                sta l1385+1
                sec 
l1385           bcs l138c
                jmp l14f2
                jmp l1414
l138c           jmp l1482
                .byte $4c, $bc, $14
                lda l17da,X
                clc 
                adc l17c8,X
                sta l17da,X
                lda l17dd,X
                adc l17cb,X
                sta l17dd,X
                jmp l14f2
                ldy l17b9,X
                lda l1702,Y
                sbc l1701,Y
                sta $fc
                lda l16a2,Y
                sbc l16a1,Y
                sta $fd
                lda l17ce,X
                cmp #$80
                and #$00
                adc l17c8,X
                tay 
l13c6           dey 
                bmi l13d0
                lsr $fd
                ror $fc
                jmp l13c6
l13d0           lda l17d1,X
                and #$01
                bne l13eb
                lda l17da,X
                clc 
                adc $fc
                sta l17da,X
                lda l17dd,X
                adc $fd
                sta l17dd,X
                jmp l13fc
l13eb           lda l17da,X
                sec 
                sbc $fc
                sta l17da,X
                lda l17dd,X
                sbc $fd
                sta l17dd,X
l13fc           lda l17ce,X
                and #$7f
                clc 
                adc #$01
                cmp l17cb,X
                bcc l140e
                inc l17d1,X
                lda #$00
l140e           sta l17ce,X
                jmp l14f2
l1414           ldy l17b9,X
                lda l1701,Y
                sta $fc
                lda l16a1,Y
                sta $fd
                lda l17da,X
                sec 
                sbc $fc
                sta l17da,X
                lda l17dd,X
                sbc $fd
                sta l17dd,X
                bmi l144c
                lda l17da,X
                sec 
                sbc l17c8,X
                sta l17da,X
                lda l17dd,X
                sbc l17cb,X
                sta l17dd,X
                bpl l146e
                jmp l1461
l144c           lda l17da,X
                clc 
                adc l17c8,X
                sta l17da,X
                lda l17dd,X
                adc l17cb,X
                sta l17dd,X
                bmi l146e
l1461           lda $fc
                sta l17da,X
                lda $fd
                sta l17dd,X
                jmp l147f
l146e           lda l17da,X
                clc 
                adc $fc
                sta l17da,X
                lda l17dd,X
                adc $fd
                sta l17dd,X
l147f           jmp l14f2
l1482           ldy l17d1,X
                dec l17c8,X
                bpl l14a5
                iny 
                lda l19d7,Y
                bmi l149b
                cmp #$70
                bmi l149b
                and #$0f
                clc 
                adc l17ce,X
                tay 
l149b           tya 
                sta l17d1,X
                lda l17cb,X
                sta l17c8,X
l14a5           lda l19d7,Y
                clc 
                adc l17b9,X
                tay 
                lda l1701,Y
                sta l17da,X
                lda l16a1,Y
                sta l17dd,X
                jmp l14f2
                .byte $de, $c8, $17, $10, $31, $bd, $cb, $17
                .byte $30, $06, $fe, $ce, $17, $4c, $d1, $14
                .byte $de, $ce, $17, $29, $7f, $9d, $c8, $17
                .byte $de, $d1, $17, $d0, $05, $a9, $00, $9d
                .byte $bc, $17, $bd, $b9, $17, $18, $7d, $ce
                .byte $17, $a8, $b9, $01, $17, $9d, $da, $17
                .byte $b9, $a1, $16, $9d, $dd, $17
l14f2           ldy l17c2,X
                lda l193e,Y
                cmp #$7f
                bne l1508
                lda l1970,Y
                cmp l17c2,X
                beq l1540
                sta l17c2,X
                tay 
l1508           lda l193e,Y
                bpl l1519
                sta l17e9,X
                lda l1957,Y
                sta l17e6,X
                jmp l152d
l1519           sta $fc
                lda l17e6,X
                clc 
                adc l1957,Y
                sta l17e6,X
                lda l17e9,X
                adc $fc
                sta l17e9,X
l152d           inc l17c5,X
                lda l17c5,X
                cmp l1970,Y
                bcc l1540
                inc l17c2,X
                lda #$00
                sta l17c5,X
l1540           ldy l17bf,X
                lda l18da,Y
                cmp #$7f
                bne l1554
                lda l190c,Y
                sta l17bf,X
                tay 
                lda l18da,Y
l1554           sta l17ec,X
                lda l190c,Y
                beq l1573
                cmp #$81
                bcs l1564
                clc 
                adc l17b9,X
l1564           and #$7f
                tay 
                lda l1701,Y
                sta l17e0,X
                lda l16a1,Y
                jmp l157c
l1573           lda l17da,X
                sta l17e0,X
                lda l17dd,X
l157c           sta l17e3,X
                inc l17bf,X
l1582           ldy l1777,X
                lda l17e0,X
                sta $d400,Y
                lda l17e3,X
                sta $d401,Y
                lda l17f2,X
                sta $d406,Y
                lda l17ef,X
                sta $d405,Y
                lda l17e6,X
                sta $d402,Y
                lda l17e9,X
                sta $d403,Y
                lda l17ec,X
                and l17f5,X
                sta $d404,Y
                lda l17f8,X
                bne l15e1
                lda l17a1,X
                beq l15e1
                lda l17bc,X
                cmp #$03
                beq l15de
                cmp #$04
                beq l15de
                lda l17a4,X
                beq l15de
                cmp #$7e
                beq l15de
                clc 
                adc l17b3,X
                cmp l17b9,X
                beq l15de
                lda #$00
                sta l17bc,X
l15de           jmp l1202
l15e1           lda l17f8,X
                bmi l15e9
                dec l17f8,X
l15e9           dex 
                bmi l15ef
                jmp l106f
l15ef           lda l178c
                bmi l1655
                beq l165a
                ldy l178e
                dec l178d
                bpl l163f
                iny 
                lda l1989,Y
                cmp #$7f
                bne l1618
                tya 
                cmp l19bd,Y
                bne l1614
                lda #$00
                sta l178c
                jmp l165a
l1614           lda l19bd,Y
                tay 
l1618           lda l1989,Y
                bpl l1639
                and #$70
                sta l1786
                lda l1989,Y
                and #$0f
                sta l178a
                lda l19a3,Y
                sta l1789
                lda l19bd,Y
                sta l1787
                jmp l1652
l1639           lda l19bd,Y
                sta l178d
l163f           lda l1789
                clc 
                adc l19a3,Y
                sta l1789
                lda l178a
                adc l1989,Y
                sta l178a
l1652           sty l178e
l1655           lda #$40
                sta l178c
l165a           lda l178a
                sta $fc
                lda l1789
                lsr $fc
                ror 
                tax 
                lsr $fc
                ror 
                lsr $fc
                ror 
                lsr $fc
                ror 
                tay 
                lda l1787
                ora l1788
                sta $d417
                sty $d416
                txa 
                and #$07
                sta $d415
                lda l1785
                ora l1786
                sta $d418
                lda l178b
                sta l1788
                rts 
l1692           sta l1782
                lda #$00
                sta l1781
                rts 
                .byte $a9, $40, $8d, $81, $17, $60
l16a1           .byte $01
l16a2           .byte $01, $01, $01, $01, $01, $01, $01, $01
                .byte $01, $01, $02, $02, $02, $02, $02, $02
                .byte $02, $03, $03, $03, $03, $03, $04, $04
                .byte $04, $04, $05, $05, $05, $06, $06, $06
                .byte $07, $07, $08, $08, $09, $09, $0a, $0a
                .byte $0b, $0c, $0d, $0d, $0e, $0f, $10, $11
                .byte $12, $13, $14, $15, $17, $18, $1a, $1b
                .byte $1d, $1f, $20, $22, $24, $27, $29, $2b
                .byte $2e, $31, $34, $37, $3a, $3e, $41, $45
                .byte $49, $4e, $52, $57, $5c, $62, $68, $6e
                .byte $75, $7c, $83, $8b, $93, $9c, $a5, $af
                .byte $b9, $c4, $d0, $dd, $ea, $f8, $fd
l1701           .byte $16
l1702           .byte $27, $38, $4b, $5f, $73, $8a, $a1, $ba
                .byte $d4, $f0, $0e, $2d, $4e, $71, $96, $bd
                .byte $e7, $13, $42, $74, $a9, $e0, $1b, $5a
                .byte $9b, $e2, $2c, $7b, $ce, $27, $85, $e8
                .byte $51, $c1, $37, $b4, $37, $c4, $57, $f5
                .byte $9c, $4e, $09, $d0, $a3, $82, $6e, $68
                .byte $6e, $88, $af, $eb, $39, $9c, $13, $a1
                .byte $46, $04, $dc, $d0, $dc, $10, $5e, $d6
                .byte $72, $38, $26, $42, $8c, $08, $b8, $a0
                .byte $b8, $20, $bc, $ac, $e4, $70, $4c, $84
                .byte $18, $10, $70, $40, $70, $40, $78, $58
                .byte $c8, $e0, $98, $08, $30, $20, $2e
l1761           .byte $99, $00, $aa, $bb, $d4, $2d, $2d, $2d
                .byte $21, $30, $4e, $45, $64, $72, $f2, $2d
l1771           .byte $00, $0c, $22, $03, $06, $09
l1777           .byte $00, $07, $0e
l177a           .byte $01, $02, $04
l177d           .byte $fe, $fd, $fb
l1780           .byte $00
l1781           .byte $80
l1782           .byte $00
l1783           .byte $00
l1784           .byte $00
l1785           .byte $0f
l1786           .byte $20
l1787           .byte $f2
l1788           .byte $00
l1789           .byte $70
l178a           .byte $05
l178b           .byte $00
l178c           .byte $00
l178d           .byte $fb
l178e           .byte $09
l178f           .byte $01, $01, $05
l1792           .byte $22, $11, $17
l1795           .byte $01, $01, $01
l1798           .byte $95, $5e, $07
l179b           .byte $1c, $06, $23
l179e           .byte $02, $01, $0f
l17a1           .byte $00, $00, $00
l17a4           .byte $00, $45, $00
l17a7           .byte $00, $a7, $10
l17aa           .byte $19, $15, $03
l17ad           .byte $00, $02, $10
l17b0           .byte $00, $00, $0c
l17b3           .byte $00, $00, $0c
l17b6           .byte $32, $18, $35
l17b9           .byte $32, $18, $41
l17bc           .byte $04, $00, $02
l17bf           .byte $03, $0d, $28
l17c2           .byte $0b, $08, $05
l17c5           .byte $01, $00, $17
l17c8           .byte $00, $00, $03
l17cb           .byte $01, $00, $05
l17ce           .byte $39, $00, $04
l17d1           .byte $39, $00, $6f
l17d4           .byte $05, $00, $00
l17d7           .byte $3a, $f6, $8a
l17da           .byte $88, $5a, $ee
l17dd           .byte $13, $04, $2d
l17e0           .byte $88, $d0, $ee
l17e3           .byte $13, $22, $2d
l17e6           .byte $10, $00, $00
l17e9           .byte $e6, $88, $f3
l17ec           .byte $41, $80, $41
l17ef           .byte $05, $0f, $00
l17f2           .byte $3a, $00, $8a
l17f5           .byte $fe, $fe, $fe
l17f8           .byte $ff
l17f9           .byte $01
l17fa           .byte $ff
l17fb           .byte $00
l17fc           .byte $0f
l17fd           .byte $05, $00, $00, $02, $02, $00, $02, $00
                .byte $00, $00, $10, $20, $a0, $e0, $d0, $00
                .byte $00, $05, $00, $00
l1811           .byte $3a, $f7, $f6, $07, $f7, $67, $88, $88
                .byte $a8, $48, $24, $3a, $25, $03, $03, $12
                .byte $8a, $66, $78, $f7
l1825           .byte $80, $c0, $c0, $c0, $c0, $00, $c0, $c0
                .byte $80, $00, $80, $80, $00, $80, $80, $a0
                .byte $80, $80, $80, $c0
l1839           .byte $00, $00, $06, $0b, $0d, $00, $0f, $10
                .byte $00, $00, $00, $00, $00, $00, $00, $0b
                .byte $00, $00, $00, $16
l184d           .byte $09, $00, $07, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $0e, $13, $07
l1861           .byte $00, $04, $09, $0e, $04, $00, $11, $16
                .byte $18, $1a, $1d, $1f, $30, $1b, $22, $24
                .byte $27, $00, $02, $2b
l1875           .byte $02, $02, $01, $01, $03, $03, $03, $03
                .byte $03, $03, $03, $03, $03, $03, $03, $03
                .byte $08, $08, $00, $00, $00, $0a, $02, $03
                .byte $03, $03, $03, $02, $02, $02, $08, $0b
                .byte $08
l1896           .byte $01, $80, $03, $04, $01, $01, $01, $01
                .byte $01, $01, $01, $01, $01, $01, $01, $01
                .byte $00, $00, $ff, $ff, $ff, $00, $01, $01
                .byte $01, $01, $01, $00, $02, $00, $00, $00
                .byte $00
l18b7           .byte $00, $00, $03, $03, $00, $04, $08, $0c
                .byte $10, $14, $18, $1c, $20, $24, $28, $2c
                .byte $28, $14, $f0, $f4, $80, $13, $c0, $30
                .byte $35, $39, $3d, $30, $00, $a0, $00, $29
                .byte $ab
l18d8           .byte $0f
l18d9           .byte $00
l18da           .byte $21, $21, $41, $7f, $81, $41, $41, $41
                .byte $7f, $81, $41, $80, $80, $7f, $81, $01
                .byte $7f, $81, $15, $11, $11, $7f, $81, $7f
                .byte $21, $7f, $21, $11, $7f, $51, $7f, $15
                .byte $40, $7f, $53, $7f, $81, $01, $7f, $41
                .byte $7f, $20, $7f, $81, $41, $40, $80, $7f
                .byte $13, $7f
l190c           .byte $80, $80, $00, $02, $c0, $a1, $9a, $00
                .byte $07, $c4, $ac, $c0, $bc, $0c, $c0, $00
                .byte $0f, $c0, $00, $76, $74, $14, $b4, $12
                .byte $00, $18, $00, $00, $1b, $00, $1d, $c5
                .byte $00, $20, $00, $22, $c0, $00, $25, $00
                .byte $27, $00, $29, $c7, $ae, $a5, $c0, $2e
                .byte $00, $30
l193e           .byte $88, $00, $81, $00, $00, $0f, $7f, $88
                .byte $7f, $88, $0f, $0f, $00, $7f, $88, $00
                .byte $0f, $00, $7f, $86, $00, $0f, $00, $0f
                .byte $7f
l1957           .byte $00, $00, $70, $40, $10, $f0, $00, $00
                .byte $00, $00, $a0, $f0, $10, $00, $00, $80
                .byte $f0, $10, $00, $00, $80, $80, $30, $d0
                .byte $00
l1970           .byte $00, $01, $00, $04, $20, $20, $04, $00
                .byte $07, $00, $05, $20, $20, $0a, $00, $0f
                .byte $30, $30, $10, $00, $10, $10, $30, $30
                .byte $16
l1989           .byte $9f, $90, $90, $90, $0f, $7f, $a4, $90
                .byte $c1, $a5, $7f, $a9, $7f, $a9, $7f, $a9
                .byte $97, $0e, $7f, $a9, $0f, $7f, $9f, $00
                .byte $e2, $7f
l19a3           .byte $00, $2c, $24, $3a, $ff, $00, $30, $4f
                .byte $70, $70, $00, $00, $00, $00, $00, $00
                .byte $00, $10, $00, $00, $a6, $00, $00, $00
                .byte $00, $00
l19bd           .byte $f2, $f2, $f2, $f2, $10, $05, $f2, $02
                .byte $f2, $f2, $0a, $f2, $0b, $f2, $01, $f2
                .byte $f2, $02, $12, $f2, $18, $15, $f2, $01
                .byte $f2, $18
l19d7           .byte $00, $fc, $f7, $70, $00, $fb, $f6, $70
                .byte $00, $fd, $f8, $70, $00, $fb, $f6, $70
                .byte $00, $fb, $f7, $70, $00, $fc, $f9, $70
                .byte $00, $fb, $f8, $70, $00, $fd, $f9, $70
                .byte $00, $fd, $fa, $70, $00, $f9, $f5, $70
                .byte $00, $fa, $f6, $70, $00, $fe, $f8, $70
                .byte $00, $fe, $f9, $f5, $70, $00, $fb, $f9
                .byte $70, $00, $fe, $f9, $70, $00, $ff, $fd
                .byte $f8, $70
l1a19           .byte $03, $04, $7f
l1a1c           .byte <l1a70, <l1a9b, <l1ab3
l1a1f           .byte >l1a70, >l1a9b, >l1ab3
l1a22           .byte <l1ad1, <l1ad5, <l1af7, <l1b97, <l1bec, <l1c57, <l1cba, <l1d3b
                .byte <l1dfc, <l1eae, <l1f30, <l1f47, <l1f5e, <l1f75, <l2028, <l204c
                .byte <l206e, <l2080, <l2099, <l20a9, <l20cb, <l212e, <l2199, <l21ba
                .byte <l21db, <l22a7, <l22b9, <l22cd, <l2325, <l23f3, <l24b1, <l2562
                .byte <l25ad, <l25b9, <l25c0, <l25e1, <l2631, <l26af, <l2730
l1a49           .byte >l1ad1, >l1ad5, >l1af7, >l1b97, >l1bec, >l1c57, >l1cba, >l1d3b
                .byte >l1dfc, >l1eae, >l1f30, >l1f47, >l1f5e, >l1f75, >l2028, >l204c
                .byte >l206e, >l2080, >l2099, >l20a9, >l20cb, >l212e, >l2199, >l21ba
                .byte >l21db, >l22a7, >l22b9, >l22cd, >l2325, >l23f3, >l24b1, >l2562
                .byte >l25ad, >l25b9, >l25c0, >l25e1, >l2631, >l26af, >l2730
l1a70           .byte $a0, $0e, $0f, $0f, $0f, $0f, $11, $01
                .byte $05, $01, $04, $ac, $02, $03, $a0, $13
                .byte $14, $13, $15, $0e, $11, $01, $05, $01
                .byte $04, $ac, $02, $1b, $a0, $13, $14, $13
                .byte $15, $1c, $1c, $1c, $1c, $ac, $02, $1f
                .byte $20, $ff, $00
l1a9b           .byte $a0, $00, $12, $06, $06, $06, $07, $25
                .byte $25, $16, $17, $06, $06, $18, $25, $25
                .byte $06, $06, $06, $06, $1d, $21, $ff, $00
l1ab3           .byte $a0, $0a, $0a, $0b, $0c, $a2, $0a, $a0
                .byte $10, $08, $09, $19, $ac, $0d, $a0, $0b
                .byte $10, $08, $09, $1a, $ac, $0d, $23, $24
                .byte $26, $a0, $1e, $22, $ff, $00
l1ad1           .byte $8f, $00, $00, $7f
l1ad5           .byte $c4, $a0, $81, $39, $39, $39, $c4, $a9
                .byte $39, $c4, $a0, $83, $39, $80, $39, $00
                .byte $83, $39, $c5, $81, $3a, $c5, $a9, $3a
                .byte $c4, $a0, $85, $39, $c4, $a9, $81, $39
                .byte $39, $7f
l1af7           .byte $ca, $a0, $81, $30, $30, $80, $30, $00
                .byte $ca, $a9, $81, $30, $ca, $a0, $83, $30
                .byte $cb, $80, $2b, $00, $c4, $85, $2d, $c4
                .byte $a9, $81, $2d, $d0, $2d, $2d, $c4, $a0
                .byte $80, $2d, $00, $81, $2d, $c4, $a9, $2d
                .byte $ca, $a0, $2e, $2e, $80, $2e, $00, $ca
                .byte $a9, $81, $2e, $ca, $a0, $83, $2e, $cb
                .byte $80, $29, $00, $c4, $85, $2b, $c4, $a9
                .byte $81, $2b, $d0, $2b, $2b, $c4, $a0, $80
                .byte $2b, $00, $81, $2b, $c4, $a9, $2b, $ca
                .byte $a0, $2d, $2d, $80, $2d, $00, $ca, $a9
                .byte $81, $2d, $ca, $a0, $83, $2d, $cb, $80
                .byte $28, $00, $c6, $85, $29, $80, $29, $00
                .byte $c6, $a9, $81, $29, $c6, $a0, $80, $29
                .byte $00, $81, $29, $c6, $a9, $29, $29, $ca
                .byte $a0, $2b, $2b, $80, $2b, $00, $ca, $a9
                .byte $81, $2b, $ca, $a0, $83, $2b, $cb, $80
                .byte $26, $00, $cc, $85, $29, $cc, $a9, $81
                .byte $29, $d0, $29, $29, $cc, $a0, $80, $29
                .byte $00, $29, $00, $cc, $a9, $81, $29, $7f
l1b97           .byte $cb, $a9, $81, $29, $cb, $a0, $80, $29
                .byte $00, $83, $29, $80, $29, $00, $cb, $a9
                .byte $81, $29, $cb, $a0, $83, $29, $80, $29
                .byte $00, $cb, $a9, $81, $29, $c8, $a0, $80
                .byte $2b, $00, $cd, $85, $2d, $cd, $a9, $81
                .byte $2d, $2d, $cb, $a0, $80, $2b, $00, $2b
                .byte $00, $83, $2b, $80, $2b, $00, $cb, $a9
                .byte $2b, $00, $cb, $a0, $2b, $00, $83, $2b
                .byte $c8, $81, $2d, $c8, $a9, $2d, $ce, $a0
                .byte $2e, $ce, $a9, $2e, $cf, $a0, $83, $30
                .byte $cf, $a9, $81, $30, $7f
l1bec           .byte $c6, $a9, $81, $35, $c6, $a0, $80, $35
                .byte $00, $35, $00, $83, $35, $80, $35, $00
                .byte $c6, $a9, $81, $35, $c6, $a0, $80, $35
                .byte $00, $c7, $83, $37, $81, $37, $c7, $a9
                .byte $37, $c6, $a0, $86, $35, $80, $00, $c9
                .byte $34, $00, $34, $00, $83, $34, $81, $34
                .byte $c9, $a9, $34, $c9, $a0, $80, $34, $00
                .byte $ca, $83, $35, $81, $35, $ca, $a9, $35
                .byte $c9, $a0, $83, $34, $80, $34, $00, $c6
                .byte $81, $30, $c6, $a9, $30, $c6, $a0, $83
                .byte $30, $c4, $80, $32, $00, $85, $32, $c4
                .byte $a9, $81, $32, $d0, $32, $32, $d0, $32
                .byte $d0, $32, $32, $d0, $32, $d0, $32, $32
                .byte $d0, $32, $7f
l1c57           .byte $c6, $a0, $81, $35, $35, $35, $c6, $a9
                .byte $35, $c6, $a0, $83, $35, $80, $35, $00
                .byte $c7, $83, $37, $80, $37, $00, $c7, $a9
                .byte $37, $00, $c6, $a0, $86, $35, $80, $00
                .byte $c8, $32, $00, $c9, $81, $34, $34, $34
                .byte $c9, $a9, $80, $34, $00, $c9, $a0, $83
                .byte $34, $80, $34, $00, $ca, $83, $35, $81
                .byte $35, $ca, $a9, $80, $35, $00, $c9, $a0
                .byte $83, $34, $80, $34, $00, $c6, $83, $30
                .byte $30, $c4, $80, $32, $00, $85, $32, $c4
                .byte $a9, $81, $32, $d0, $32, $32, $d0, $32
                .byte $d0, $32, $32, $d0, $32, $d0, $32, $32
                .byte $d0, $32, $7f
l1cba           .byte $a1, $83, $11, $a6, $81, $3c, $a7, $45
                .byte $a2, $18, $a7, $48, $a4, $80, $11, $00
                .byte $a1, $83, $11, $81, $00, $a6, $3c, $a7
                .byte $43, $a2, $18, $a7, $48, $a4, $83, $15
                .byte $a1, $1a, $a6, $81, $39, $a7, $41, $a2
                .byte $18, $a7, $48, $a4, $80, $1a, $00, $a1
                .byte $83, $1a, $81, $00, $a6, $39, $a7, $3e
                .byte $a2, $18, $a7, $48, $a4, $1f, $90, $13
                .byte $00, $a1, $83, $15, $a6, $81, $3c, $a7
                .byte $40, $a2, $18, $a7, $48, $a4, $80, $15
                .byte $00, $a1, $83, $15, $81, $00, $a6, $34
                .byte $a7, $3c, $a2, $18, $a7, $45, $a3, $24
                .byte $a1, $15, $83, $16, $a6, $81, $3a, $a7
                .byte $41, $a2, $18, $a7, $4a, $a4, $16, $a1
                .byte $83, $0a, $81, $00, $a6, $35, $a7, $3e
                .byte $a2, $18, $a7, $46, $a4, $18, $91, $1a
                .byte $7f
l1d3b           .byte $a1, $83, $18, $a6, $81, $43, $a7, $48
                .byte $a2, $83, $18, $a4, $80, $18, $00, $a1
                .byte $83, $11, $80, $1d, $00, $a6, $81, $43
                .byte $a7, $45, $a2, $18, $a1, $15, $a4, $18
                .byte $91, $17, $a1, $83, $16, $a6, $81, $41
                .byte $a7, $46, $a2, $83, $18, $a4, $80, $16
                .byte $00, $a1, $81, $1b, $91, $16, $0f, $a7
                .byte $41, $a6, $43, $a2, $18, $a1, $1f, $a4
                .byte $1b, $91, $1a, $a1, $83, $19, $a6, $81
                .byte $40, $a1, $15, $a2, $18, $a4, $10, $95
                .byte $0e, $81, $1a, $a6, $40, $a7, $41, $a2
                .byte $18, $a1, $15, $a3, $24, $a1, $80, $15
                .byte $00, $83, $17, $a6, $81, $3e, $a7, $43
                .byte $a2, $83, $18, $a4, $80, $11, $00, $a1
                .byte $85, $13, $a6, $81, $3b, $a7, $41, $a2
                .byte $18, $a1, $80, $11, $00, $a4, $81, $13
                .byte $91, $15, $a1, $83, $16, $a6, $81, $3a
                .byte $a7, $3e, $a2, $18, $a7, $45, $a4, $80
                .byte $11, $00, $a1, $85, $0a, $a7, $81, $3a
                .byte $a6, $3e, $a2, $18, $a6, $43, $a3, $83
                .byte $24, $a1, $18, $a6, $81, $3c, $a7, $40
                .byte $a2, $18, $a7, $45, $a4, $80, $13, $00
                .byte $a1, $85, $0c, $a6, $81, $37, $a7, $3c
                .byte $b3, $18, $a7, $83, $43, $b3, $81, $18
                .byte $7f
l1dfc           .byte $87, $00, $a8, $80, $37, $c0, $92, $39
                .byte $c3, $81, $7e, $00, $83, $37, $00, $35
                .byte $c3, $81, $7e, $00, $83, $34, $c0, $93
                .byte $35, $00, $c1, $37, $00, $80, $32, $c0
                .byte $94, $34, $81, $00, $c1, $83, $30, $c3
                .byte $7e, $89, $00, $80, $2d, $00, $83, $30
                .byte $c0, $93, $32, $c1, $34, $c0, $91, $35
                .byte $c3, $85, $7e, $c1, $81, $32, $83, $00
                .byte $aa, $81, $3c, $90, $3e, $00, $43, $00
                .byte $d1, $35, $00, $81, $41, $d1, $80, $3a
                .byte $00, $3e, $00, $81, $3c, $91, $3e, $91
                .byte $3c, $d1, $80, $35, $88, $00, $a8, $80
                .byte $37, $c0, $92, $39, $c3, $81, $7e, $00
                .byte $83, $3c, $00, $35, $c3, $81, $7e, $00
                .byte $83, $34, $c0, $93, $35, $00, $c1, $37
                .byte $00, $39, $00, $80, $36, $c0, $94, $37
                .byte $c3, $81, $7e, $89, $00, $80, $30, $00
                .byte $35, $c0, $92, $37, $93, $39, $c1, $34
                .byte $35, $c3, $7e, $81, $3e, $83, $00, $aa
                .byte $81, $3c, $90, $3e, $00, $45, $00, $d1
                .byte $3a, $00, $81, $41, $90, $3e, $00, $d1
                .byte $35, $00, $a8, $3c, $c0, $92, $3e, $93
                .byte $3c, $7f
l1eae           .byte $c3, $84, $7e, $82, $00, $a8, $80, $39
                .byte $c0, $92, $3a, $93, $39, $c3, $7e, $00
                .byte $80, $35, $c0, $92, $37, $93, $35, $c3
                .byte $7e, $00, $80, $30, $c0, $92, $32, $93
                .byte $2e, $c3, $84, $7e, $88, $00, $80, $2d
                .byte $00, $83, $31, $c0, $91, $32, $c1, $80
                .byte $34, $82, $00, $81, $37, $83, $35, $c3
                .byte $7e, $81, $32, $80, $2d, $00, $37, $c0
                .byte $92, $39, $97, $37, $c3, $83, $7e, $85
                .byte $00, $80, $32, $00, $34, $c0, $92, $35
                .byte $91, $34, $c1, $32, $00, $30, $83, $32
                .byte $c3, $87, $7e, $83, $00, $80, $32, $00
                .byte $34, $00, $34, $c0, $92, $35, $91, $34
                .byte $c1, $80, $32, $82, $00, $81, $30, $80
                .byte $32, $c0, $92, $34, $c3, $83, $7e, $91
                .byte $32, $90, $33, $90, $32, $93, $30, $c3
                .byte $7e, $7f
l1f30           .byte $ab, $81, $29, $c2, $7e, $29, $83, $35
                .byte $29, $81, $29, $c2, $7e, $29, $29, $35
                .byte $d2, $7e, $83, $29, $81, $27, $7f
l1f47           .byte $ab, $81, $29, $c2, $7e, $29, $83, $35
                .byte $29, $81, $29, $c2, $7e, $29, $29, $35
                .byte $d2, $7e, $83, $29, $81, $28, $7f
l1f5e           .byte $ab, $81, $29, $c2, $7e, $29, $83, $35
                .byte $29, $81, $29, $c2, $7e, $29, $29, $35
                .byte $d2, $7e, $83, $29, $81, $2d, $7f
l1f75           .byte $b0, $80, $37, $d6, $92, $39, $c3, $8f
                .byte $00, $80, $30, $00, $30, $00, $81, $30
                .byte $91, $32, $91, $35, $80, $37, $00, $37
                .byte $d6, $92, $39, $c1, $81, $3c, $c3, $8d
                .byte $00, $80, $30, $00, $30, $00, $81, $30
                .byte $91, $32, $90, $35, $00, $37, $00, $32
                .byte $d6, $92, $34, $c1, $80, $35, $00, $32
                .byte $d6, $93, $34, $c3, $82, $00, $c1, $80
                .byte $30, $00, $32, $d6, $92, $34, $80, $35
                .byte $00, $32, $d6, $94, $34, $91, $35, $c1
                .byte $32, $00, $c3, $8f, $00, $81, $00, $80
                .byte $30, $00, $30, $00, $81, $30, $91, $32
                .byte $91, $35, $80, $37, $00, $37, $d6, $92
                .byte $39, $c3, $8f, $00, $c1, $80, $39, $00
                .byte $39, $00, $81, $39, $91, $3a, $91, $3c
                .byte $80, $39, $00, $35, $d6, $92, $37, $c1
                .byte $81, $35, $c3, $89, $00, $80, $3e, $d6
                .byte $92, $40, $91, $3e, $00, $3c, $d6, $91
                .byte $3e, $91, $3c, $c3, $86, $7e, $88, $00
                .byte $80, $30, $00, $81, $39, $c3, $7e, $91
                .byte $3a, $00, $3c, $80, $37, $d6, $90, $39
                .byte $c1, $93, $35, $c3, $84, $7e, $8f, $00
                .byte $8a, $00, $7f
l2028           .byte $d3, $ac, $80, $41, $82, $00, $80, $7e
                .byte $00, $7e, $82, $00, $80, $7e, $82, $00
                .byte $80, $7e, $82, $00, $80, $7e, $00, $7e
                .byte $00, $7e, $82, $00, $80, $7e, $82, $00
                .byte $80, $7e, $00, $7f
l204c           .byte $80, $7e, $82, $00, $80, $7e, $00, $7e
                .byte $82, $00, $80, $7e, $82, $00, $80, $7e
                .byte $82, $00, $80, $7e, $00, $7e, $00, $7e
                .byte $82, $00, $80, $7e, $82, $00, $80, $7e
                .byte $00, $7f
l206e           .byte $ab, $81, $29, $c2, $7e, $29, $83, $35
                .byte $29, $81, $29, $c2, $87, $7e, $cb, $ad
                .byte $3a, $7f
l2080           .byte $80, $7e, $82, $00, $80, $7e, $00, $7e
                .byte $82, $00, $80, $7e, $82, $00, $80, $7e
                .byte $88, $00, $d4, $ae, $86, $37, $80, $00
                .byte $7f
l2099           .byte $8f, $00, $87, $00, $d5, $af, $80, $3c
                .byte $3c, $3c, $3c, $3c, $3c, $3c, $3c, $7f
l20a9           .byte $c4, $b1, $81, $39, $39, $39, $c4, $a9
                .byte $39, $c4, $b1, $83, $39, $80, $39, $00
                .byte $83, $39, $c5, $81, $3a, $c5, $a9, $3a
                .byte $c4, $b1, $85, $39, $c4, $a9, $81, $39
                .byte $39, $7f
l20cb           .byte $c6, $b1, $81, $35, $35, $35, $c6, $a9
                .byte $35, $c6, $b1, $83, $35, $80, $35, $00
                .byte $c7, $83, $37, $80, $37, $00, $c7, $a9
                .byte $37, $00, $c6, $b1, $86, $35, $80, $00
                .byte $c8, $32, $00, $c9, $81, $34, $34, $34
                .byte $c9, $a9, $80, $34, $00, $c9, $b1, $83
                .byte $34, $80, $34, $00, $ca, $83, $35, $81
                .byte $35, $ca, $a9, $80, $35, $00, $c9, $b1
                .byte $83, $34, $80, $34, $00, $c6, $83, $30
                .byte $30, $c4, $80, $32, $00, $85, $32, $c4
                .byte $a9, $81, $32, $d0, $32, $32, $d0, $32
                .byte $d0, $32, $32, $d0, $32, $d0, $32, $32
                .byte $d0, $32, $7f
l212e           .byte $c6, $a9, $81, $35, $c6, $b1, $80, $35
                .byte $00, $35, $00, $83, $35, $80, $35, $00
                .byte $c6, $a9, $81, $35, $c6, $b1, $80, $35
                .byte $00, $c7, $83, $37, $81, $37, $c7, $a9
                .byte $37, $c6, $b1, $86, $35, $80, $00, $c9
                .byte $34, $00, $34, $00, $83, $34, $81, $34
                .byte $c9, $a9, $34, $c9, $b1, $80, $34, $00
                .byte $ca, $83, $35, $81, $35, $ca, $a9, $35
                .byte $c9, $b1, $83, $34, $80, $34, $00, $c6
                .byte $81, $30, $c6, $a9, $30, $c6, $b1, $83
                .byte $30, $c4, $80, $32, $00, $85, $32, $c4
                .byte $a9, $81, $32, $d0, $32, $32, $d0, $32
                .byte $d0, $32, $32, $d0, $32, $d0, $32, $32
                .byte $d0, $32, $7f
l2199           .byte $a1, $83, $11, $a6, $81, $3c, $a7, $45
                .byte $a2, $18, $a7, $48, $a4, $80, $11, $00
                .byte $a1, $83, $11, $81, $00, $a6, $3c, $a7
                .byte $43, $a2, $18, $a7, $48, $a4, $83, $18
                .byte $7f
l21ba           .byte $a1, $83, $11, $a6, $81, $3c, $a7, $41
                .byte $a2, $18, $a7, $48, $a4, $80, $11, $00
                .byte $a1, $83, $11, $81, $00, $a6, $3c, $a7
                .byte $43, $a2, $18, $a7, $48, $a4, $83, $18
                .byte $7f
l21db           .byte $a1, $83, $1c, $a6, $81, $43, $a7, $48
                .byte $a2, $18, $a4, $10, $a3, $80, $18, $00
                .byte $a1, $83, $11, $80, $1d, $00, $a6, $81
                .byte $43, $a7, $45, $a2, $18, $a1, $15, $a4
                .byte $1d, $91, $1b, $a1, $83, $1a, $a6, $81
                .byte $41, $a1, $1d, $a2, $83, $0e, $a4, $80
                .byte $16, $00, $a1, $81, $1b, $91, $16, $83
                .byte $0f, $a6, $81, $43, $a2, $18, $a1, $1f
                .byte $a4, $1b, $91, $1a, $a1, $83, $19, $a6
                .byte $81, $40, $a1, $15, $a2, $18, $a4, $10
                .byte $95, $0e, $81, $1a, $a6, $40, $a7, $41
                .byte $a2, $18, $a1, $15, $a3, $24, $a1, $80
                .byte $15, $00, $83, $17, $a6, $81, $3e, $a7
                .byte $43, $a2, $83, $18, $a4, $80, $11, $00
                .byte $a1, $85, $13, $a6, $81, $3b, $a7, $41
                .byte $a2, $18, $a1, $80, $11, $00, $a4, $81
                .byte $13, $91, $15, $a1, $83, $16, $a6, $81
                .byte $3a, $a7, $3e, $a2, $18, $a7, $45, $a4
                .byte $80, $11, $00, $a1, $85, $0a, $a7, $81
                .byte $3a, $a6, $3e, $a2, $18, $a6, $43, $a3
                .byte $83, $24, $a1, $18, $a6, $81, $3c, $a7
                .byte $40, $a2, $18, $a7, $45, $a4, $80, $13
                .byte $00, $a1, $85, $0c, $a6, $81, $37, $a7
                .byte $3c, $a2, $18, $a1, $89, $0c, $83, $00
                .byte $d5, $af, $80, $3c, $3c, $3c, $3c, $3c
                .byte $3c, $3c, $3c, $7f
l22a7           .byte $83, $00, $b0, $80, $3c, $00, $3c, $00
                .byte $81, $3c, $91, $3e, $91, $41, $80, $43
                .byte $00, $7f
l22b9           .byte $8f, $00, $83, $00, $b0, $80, $3c, $00
                .byte $3c, $00, $81, $3c, $91, $3d, $91, $41
                .byte $80, $48, $00, $7f
l22cd           .byte $cb, $a9, $81, $29, $cb, $a0, $80, $29
                .byte $00, $83, $29, $80, $29, $00, $cb, $a9
                .byte $81, $29, $cb, $a0, $83, $29, $80, $29
                .byte $00, $cb, $a9, $81, $29, $c8, $a0, $80
                .byte $2b, $00, $cd, $85, $2d, $cd, $a9, $81
                .byte $2d, $2d, $cb, $a0, $80, $2b, $00, $2b
                .byte $00, $83, $2b, $80, $2b, $00, $cb, $a9
                .byte $2b, $00, $cb, $a0, $2b, $00, $83, $2b
                .byte $c8, $81, $2d, $c8, $a9, $2d, $ce, $a0
                .byte $2e, $ce, $a9, $2e, $d7, $a0, $89, $30
                .byte $83, $00, $81, $30, $00, $30, $00, $7f
l2325           .byte $c4, $a0, $80, $34, $82, $00, $c4, $a9
                .byte $81, $34, $c4, $a0, $80, $34, $82, $00
                .byte $c4, $a9, $81, $34, $c4, $a0, $80, $34
                .byte $82, $00, $c4, $a9, $81, $34, $c4, $a0
                .byte $80, $34, $82, $00, $c4, $a9, $80, $34
                .byte $00, $c4, $a0, $34, $82, $00, $c4, $a9
                .byte $80, $34, $00, $34, $00, $d8, $a0, $35
                .byte $82, $00, $d8, $a9, $81, $35, $d8, $a0
                .byte $80, $35, $82, $00, $d8, $a9, $81, $35
                .byte $d8, $a0, $80, $35, $82, $00, $d8, $a9
                .byte $81, $35, $d8, $a0, $80, $35, $82, $00
                .byte $d8, $a9, $81, $35, $d8, $a0, $80, $35
                .byte $82, $00, $81, $35, $d8, $a9, $35, $d9
                .byte $a0, $80, $32, $82, $00, $d9, $a9, $81
                .byte $32, $d9, $a0, $80, $32, $82, $00, $d9
                .byte $a9, $81, $32, $d9, $a0, $80, $32, $82
                .byte $00, $d9, $a9, $81, $32, $d9, $a0, $80
                .byte $32, $82, $00, $d9, $a9, $81, $32, $d9
                .byte $a0, $80, $32, $82, $00, $d9, $a9, $81
                .byte $32, $32, $d8, $a0, $80, $32, $82, $00
                .byte $d8, $a9, $81, $32, $d8, $a0, $80, $32
                .byte $82, $00, $d8, $a9, $81, $32, $d8, $a0
                .byte $80, $32, $82, $00, $d8, $a9, $81, $32
                .byte $d8, $a0, $80, $32, $82, $00, $d8, $a9
                .byte $81, $32, $d8, $a0, $80, $32, $82, $00
                .byte $81, $35, $d8, $a9, $35, $7f
l23f3           .byte $a1, $83, $18, $a6, $81, $43, $a7, $48
                .byte $a2, $83, $18, $a4, $80, $18, $00, $a1
                .byte $83, $11, $80, $1d, $00, $a6, $81, $43
                .byte $a7, $45, $a2, $18, $a1, $15, $a4, $18
                .byte $91, $17, $a1, $83, $16, $a6, $81, $41
                .byte $a7, $46, $a2, $83, $18, $a4, $80, $16
                .byte $00, $a1, $81, $1b, $91, $16, $0f, $a7
                .byte $41, $a6, $43, $a2, $18, $a1, $1f, $a4
                .byte $1b, $91, $1a, $a1, $83, $19, $a6, $81
                .byte $40, $a1, $15, $a2, $18, $a4, $10, $95
                .byte $0e, $81, $1a, $a6, $40, $a7, $41, $a2
                .byte $18, $a1, $15, $a3, $24, $a1, $80, $15
                .byte $00, $83, $17, $a6, $81, $3e, $a7, $43
                .byte $a2, $83, $18, $a4, $80, $11, $00, $a1
                .byte $85, $13, $a6, $81, $3b, $a7, $41, $a2
                .byte $18, $a1, $80, $11, $00, $a4, $81, $13
                .byte $91, $15, $a1, $83, $16, $a6, $81, $3a
                .byte $a7, $3e, $a2, $18, $a7, $45, $a4, $80
                .byte $11, $00, $a1, $85, $0a, $a7, $81, $3a
                .byte $a6, $3e, $a2, $18, $a6, $43, $a3, $83
                .byte $24, $a1, $18, $a6, $81, $3c, $a7, $40
                .byte $a2, $18, $a7, $45, $a4, $80, $13, $00
                .byte $a1, $85, $0c, $a6, $81, $37, $a7, $3c
                .byte $a2, $18, $a1, $85, $0c, $7f
l24b1           .byte $c3, $84, $7e, $82, $00, $a8, $80, $39
                .byte $c0, $92, $3a, $93, $39, $c3, $7e, $00
                .byte $80, $35, $c0, $92, $37, $93, $35, $c3
                .byte $81, $7e, $33, $32, $00, $80, $30, $c0
                .byte $90, $32, $c1, $81, $35, $93, $2e, $c3
                .byte $84, $7e, $80, $00, $81, $26, $c0, $91
                .byte $27, $c1, $2b, $91, $2e, $91, $32, $93
                .byte $31, $c0, $91, $32, $c1, $80, $34, $82
                .byte $00, $81, $39, $80, $34, $92, $35, $81
                .byte $34, $32, $00, $80, $2d, $00, $37, $c0
                .byte $90, $39, $c1, $91, $3c, $80, $39, $c0
                .byte $92, $3b, $90, $3a, $c1, $90, $39, $91
                .byte $37, $c3, $83, $7e, $85, $00, $a8, $80
                .byte $32, $00, $34, $c0, $92, $35, $91, $34
                .byte $c1, $32, $00, $30, $83, $32, $c3, $87
                .byte $7e, $83, $00, $80, $32, $00, $34, $00
                .byte $34, $c0, $92, $35, $91, $34, $c1, $80
                .byte $32, $82, $00, $81, $30, $80, $30, $c0
                .byte $92, $32, $c3, $87, $7e, $81, $00, $80
                .byte $2d, $00, $32, $00, $34, $00, $34, $c0
                .byte $92, $35, $81, $34, $c1, $80, $32, $82
                .byte $00, $80, $30, $00, $30, $c0, $92, $32
                .byte $7f
l2562           .byte $cb, $a9, $81, $29, $cb, $a0, $80, $29
                .byte $00, $83, $29, $80, $29, $00, $cb, $a9
                .byte $81, $29, $cb, $a0, $83, $29, $80, $29
                .byte $00, $cb, $a9, $81, $29, $c8, $a0, $80
                .byte $2b, $00, $cd, $85, $2d, $cd, $a9, $81
                .byte $2d, $2d, $cb, $a0, $80, $2b, $00, $2b
                .byte $00, $83, $2b, $80, $2b, $00, $cb, $a9
                .byte $2b, $00, $cb, $a0, $2b, $00, $83, $2b
                .byte $c8, $81, $2d, $c8, $a9, $2d, $cb, $a0
                .byte $89, $2b, $7f
l25ad           .byte $da, $a0, $8f, $29, $83, $7e, $8f, $00
                .byte $00, $8b, $00, $7f
l25b9           .byte $a1, $8f, $0e, $7e, $00, $00, $7f
l25c0           .byte $c3, $89, $7e, $e0, $90, $30, $df, $90
                .byte $2d, $90, $2c, $90, $2b, $90, $29, $90
                .byte $26, $90, $24, $90, $21, $90, $20, $90
                .byte $1f, $90, $1d, $9f, $1a, $7e, $8a, $7e
                .byte $7f
l25e1           .byte $8f, $00, $00, $00, $00, $00, $00, $00
                .byte $87, $00, $b2, $85, $22, $db, $9d, $24
                .byte $c3, $8b, $7e, $83, $00, $81, $21, $1d
                .byte $80, $24, $dd, $9a, $26, $93, $29, $c3
                .byte $87, $7e, $dd, $97, $2d, $97, $2b, $c3
                .byte $7e, $85, $00, $80, $26, $00, $81, $29
                .byte $91, $2b, $91, $30, $80, $29, $dd, $92
                .byte $2b, $95, $29, $c3, $89, $7e, $83, $00
                .byte $80, $26, $00, $81, $29, $91, $2b, $91
                .byte $35, $b2, $80, $32, $dd, $90, $34, $7f
l2631           .byte $81, $7e, $c0, $95, $30, $c3, $87, $7e
                .byte $80, $35, $c0, $92, $37, $97, $34, $c1
                .byte $80, $39, $dc, $90, $3b, $c1, $91, $3c
                .byte $c1, $91, $39, $80, $37, $00, $32, $c0
                .byte $90, $34, $91, $32, $c1, $91, $30, $90
                .byte $2d, $90, $2b, $c3, $97, $29, $81, $00
                .byte $2e, $91, $2d, $91, $30, $b2, $29, $c0
                .byte $95, $2b, $c1, $80, $2d, $84, $00, $80
                .byte $29, $c0, $90, $2b, $c3, $83, $7e, $80
                .byte $2d, $82, $00, $80, $24, $de, $00, $81
                .byte $2b, $c2, $83, $7e, $80, $2d, $82, $00
                .byte $80, $22, $de, $00, $81, $2b, $90, $2c
                .byte $90, $2b, $91, $29, $80, $2d, $00, $30
                .byte $de, $00, $1d, $de, $00, $81, $2b, $c3
                .byte $83, $7e, $80, $30, $00, $32, $de, $00
                .byte $26, $de, $00, $85, $2d, $7f
l26af           .byte $a1, $83, $11, $a6, $81, $3c, $a7, $45
                .byte $b3, $18, $a7, $48, $a4, $80, $11, $00
                .byte $a1, $83, $11, $81, $00, $a6, $3c, $a7
                .byte $43, $b3, $18, $a7, $48, $a4, $83, $15
                .byte $a1, $1a, $a6, $81, $39, $a7, $41, $b3
                .byte $18, $a7, $48, $a4, $80, $1a, $00, $a1
                .byte $83, $1a, $81, $00, $a6, $39, $a7, $3e
                .byte $b3, $18, $a7, $48, $a4, $1f, $90, $13
                .byte $00, $a1, $83, $15, $a6, $81, $3c, $a7
                .byte $40, $b3, $18, $a7, $48, $a4, $80, $15
                .byte $00, $a1, $83, $15, $81, $00, $a6, $34
                .byte $a7, $3c, $b3, $18, $a7, $45, $a3, $24
                .byte $a1, $15, $83, $16, $a6, $81, $3a, $a7
                .byte $41, $b3, $18, $a7, $4a, $a4, $16, $a1
                .byte $83, $0a, $81, $00, $a6, $35, $a7, $3e
                .byte $b3, $18, $a7, $46, $a4, $18, $91, $1a
                .byte $7f
l2730           .byte $80, $34, $00, $35, $de, $00, $29, $de
                .byte $00, $81, $30, $c2, $83, $7e, $80, $37
                .byte $90, $39, $3c, $de, $00, $2d, $de, $00
                .byte $81, $34, $c2, $83, $7e, $80, $3e, $00
                .byte $39, $de, $00, $43, $de, $00, $b2, $3b
                .byte $dc, $91, $3c, $c3, $82, $7e, $81, $3a
                .byte $c0, $91, $39, $c1, $91, $37, $dc, $91
                .byte $35, $91, $37, $c1, $39, $80, $39, $c0
                .byte $90, $3a, $91, $39, $c1, $91, $32, $91
                .byte $39, $91, $35, $91, $2e, $91, $37, $80
                .byte $32, $c0, $92, $34, $c3, $81, $7e, $90
                .byte $33, $90, $32, $91, $30, $c3, $83, $7e
                .byte $00, $80, $32, $c0, $90, $34, $91, $32
                .byte $c1, $30, $80, $37, $00, $34, $c0, $90
                .byte $35, $91, $34, $c0, $95, $32, $c0, $91
                .byte $30, $93, $32, $c3, $87, $7e, $85, $00
                .byte $a8, $80, $2e, $00, $30, $c0, $92, $32
                .byte $93, $30, $7f
