; ==========================================================================
; Galway SF2 driver — B2/B3: 3-voice sequencer with orderlist chaining
; ==========================================================================
; Native SID Factory II driver (descriptor type 0x00). Three voices, each
; walking its own ORDERLIST (a list of pattern indices + transpose) -> the
; sequence-pointer table -> packed sequences (notes/instruments/durations).
; Plays arbitrary multi-pattern songs. Galway's real FM/PM synth comes next.
;
; Build: py -3 bin/build_galway_driver_full.py
; ==========================================================================
        .cpu "6502"

SID         = $d400
SID_VOL     = $d418

; --- digi engine state (DIGI_SPIKE=1): trigger-driven sample player ---
; ZP at $c9-$cc: FREE between the music's vtrans ($c6-$c8) and vfreq ($d0). MUST
; NOT reuse the music's ZP ($f0-$f4 = ms_cnt/tieflag/np_guard/pending_dur) — the
; music runs BEFORE the digi each frame and would clobber these pointers.
dtp         = $c9         ; ZP: 16-bit pointer into digi_triggers (2)
dbp         = $cb         ; ZP: 16-bit pointer into digi_bank (active sample) (2)
nptr        = $cd         ; ZP: 16-bit pointer into digi_nco_tab (HYBRID lead) (2)
dcdown      = $1900       ; frames until the next trigger fires
dcnt        = $1901       ; 16-bit samples remaining in the active sample (2)
dwc         = $1903       ; $D418 writes left this frame
dfg         = $1904       ; anti-runaway: max chained (delta-0) fires per frame
; --- DIGI_NCO=1: sawtooth-oscillator melody (Arkanoid's digi is a continuous
;     sawtooth LEAD, not drums). nptr walks a per-frame 8-bit phase-increment
;     table; the NCO phase-accumulates per $D418 write. nptr reuses dtp's ZP. ---
nphase      = $1905       ; NCO 8-bit phase accumulator
nincr       = $1906       ; this frame's phase increment (= step<<4; 0 = rest)
nldx        = $1907       ; this frame's inter-write delay (small = FAST write gap)
ncnt        = $1908       ; this frame's lead write count (source count, cycle-capped)
nsegs       = $1909       ; DIGI_SWEEP: gap-sweep segment count this frame
segc        = $190a       ; DIGI_SWEEP: segments remaining (loop counter)
nrep        = $190b       ; DIGI_RLE: frames left to hold the current record
pincr       = $190c       ; DIGI_SWEEP: previous frame's step (detect note onset)
; Lead = a 4-bit-accumulator sawtooth regenerated by a TIGHT NCO loop (nphase += nincr
; per write, output = high nibble). incr = step<<4 reproduces the source's exact step
; pattern; the loop is tight enough to write at the source's FAST ~32-40 cyc gap, which
; is what makes reSID render the right (smoothed) pitch. Table = 3 B/frame (incr,ldx,count).

; per-voice state (indexed 0..2)
vsp_lo      = $e0           ; current sequence ptr lo
vsp_hi      = $e3           ; current sequence ptr hi
vwf         = $e6           ; current waveform byte
vhold       = $e9           ; sustain countdown (rows to hold)
vol_lo      = $c0           ; orderlist read ptr lo
vol_hi      = $c3           ; orderlist read ptr hi
vtrans      = $c6           ; current transpose offset (signed)
vpwbase     = $b0           ; $b0,$b1,$b2  per-voice pulse-width base (hi byte)
vfreq_lo    = $d0           ; $d0,$d1,$d2  per-voice base note frequency lo
vfreq_hi    = $d3           ; $d3,$d4,$d5  per-voice base note frequency hi
vib_phase   = $d6           ; $d6,$d7,$d8  per-voice vibrato phase
vib_delay   = $d9           ; $d9,$da,$db  frames before vibrato starts
VIBSPD   = $10           ; vibrato phase increment per frame
VIBDLY   = $0c           ; delay (frames) before vibrato kicks in
; scratch
wptr        = $fa           ; working pointer (seq / orderlist)
fmptr       = $ec           ; working pointer into FMTAB (fm_step indirect read) (2)
pptr        = $b9           ; working pointer into PULSETAB (pulse_step indirect read) (2)
                            ; ($ea/$eb collide with vhold[1]/vhold[2]!)
ms_cnt      = $f0           ; multispeed tick countdown within one video frame
tmpf        = $f6           ; freq/ADSR temp (lo/hi)
widx        = $f5           ; wave-index temp
pending_dur = $f4           ; duration parsed this event
tieflag     = $f1           ; nonzero if the current note is a TIE ($90-$9f dur):
                            ; legato continuation -> no gate re-attack, pulse free-runs
np_guard    = $f3           ; orderlist-walk guard (anti-runaway)
sidoff      = $f8           ; SID register offset for current voice
zp_guard    = $f9           ; sequence-parse guard (anti-runaway)
zp_tcnt     = $fc           ; shared tempo countdown
; pulse-width modulation: faithful to Galway — the 12-bit pulse HI byte is FIXED
; at the instrument's base and the LO byte sweeps as a triangle. Matches the real
; Wizball trace (pw_hi $08 held; pw_lo ramps +8/frame), not the old coarse
; hi-nibble swing. Per-voice current-lo + sweep direction.
pw_lo       = $b3           ; $b3,$b4,$b5  per-voice current pulse-width lo
pw_dir      = $b6           ; $b6,$b7,$b8  0 = sweeping up, 1 = down
PWSTEP   = $08           ; pulse-width lo delta per frame (Galway uses +8)
PWMIN    = $08
PWMAX    = $f8
; --- filter (one global SID resource): high-resonance low-pass with a downward
;     cutoff sweep that RESTARTS on each routed-voice note. Tuned to Galway's
;     real Wizball filter (res $F, voice-1 routed, LP, cutoff $8900->$7300). ---
filt_lo     = $bc           ; 16-bit current cutoff lo
filt_hi     = $bd           ; 16-bit current cutoff hi (high byte -> $D416)
FILT_RES   = $f0         ; resonance (high nibble of $D417 res_control)
FILT_ROUTE = $01         ; voices routed to the filter (bit n = voice n); v0 lead
FILT_MODE  = $10         ; low-pass mode (OR'd into $D418 with the volume nibble)
FILTTOP    = $8900       ; cutoff sweep start (reset on each routed note)
FILTBOT    = $7300       ; cutoff sweep floor
FILTSTEP   = $00c0       ; cutoff decrement per frame (16-bit; ~0.75 hi/frame)
; --- wave program runner (STANDARD SF2II wave table, col-major 256x2:
;     col0=waveform byte, col1=semitone(00-7f add / 80-df abs) or jump-target;
;     one row advanced per frame; col0 $7f = jump to col1 index). The editor
;     renders these programs and the driver plays them. State in scratch RAM
;     ($1800-$18xx, free between the driver end and the edit area). -----------
VWI     = $1800          ; per-voice current wave-program row (3)
VGMASK  = $1803          ; per-voice $D404 AND-mask: $ff gated-on, $fe gated-off (3)
VIWAVE  = $1806          ; per-voice instrument wave-program start row (3)
ws_row  = $ee            ; wave_step scratch: resolved row
ws_grd  = $ef            ; wave_step scratch / pulse_step $7f-jump guard
; --- pulse program runner (ROW-major PULSETAB, 3 bytes/entry, walked via a
;     16-bit pointer exactly like FM — removes the old 256-row col-major cap so a
;     full-length song's pulse envelopes (1000s of frames -> 100s of rows) fit:
;     8X XX YY = set 12-bit width (X|XX) for YY frames; 0X XX YY = add (X|XX) to
;     width each frame for YY; 7f -- -- = freeze (end). The per-note pulse program
;     is selected by the $c0-$ff command (index -> IPULSE_LO/HI -> VIPUL -> PPTR),
;     decoupled from the instrument. (No longer a render-in-editor table.) -------
VPC     = $180c          ; per-voice frames left on current row (3)
VPLO    = $180f          ; per-voice current 12-bit pulse lo (3)
VPHI    = $1812          ; per-voice current 12-bit pulse hi (3)
VPADL   = $1815          ; per-voice per-frame add lo (3)
VPADH   = $1818          ; per-voice per-frame add hi (3)
; --- filter program runner (STANDARD SF2II filter table, col-major 256x3:
;     9Y YY RB = set passband/cutoff/res/bitmask; 0X XX YY = add to cutoff each
;     frame for YY; 7f -- XX = jump. ONE global SID filter; started when a note
;     from an instrument with flag $40 triggers (filter index = instr col3).
;     Cutoff held as 16-bit F_CUT (high byte -> $D416). -----------------------
F_IDX   = $181e          ; filter-program row
F_CNT   = $181f          ; frames left on current row
F_CLO   = $1820          ; 16-bit cutoff lo
F_CHI   = $1821          ; 16-bit cutoff hi (-> $D416)
F_ADLO  = $1822          ; per-frame cutoff add lo
F_ADHI  = $1823          ; per-frame cutoff add hi
F_MODE  = $1824          ; SID mode bits for $D418 high nibble (from passband)
F_ACT   = $1825          ; 1 = a filter program is running
VIFLAGS = $1826          ; per-voice instrument flags byte (col2) (3)
VIFILT  = $1829          ; per-voice instrument filter-program start row (3)
; --- FM offset-list runner (TRACE-DRIVEN pitch program): per-voice frequency
;     accumulator that walks the FM table (FMTAB ROW-major, 3 bytes/entry:
;     lo,hi,dur) via a 16-bit pointer from the note's instrument FM-start,
;     adding the signed offset to FM_ACC each frame; freq written = vfreq +
;     FM_ACC. dur 0 = freeze. Row-major + 16-bit ptr removes the old 256-entry
;     cap so full-length Galway slides (1000s of frames) fit. Each note's pitch
;     envelope is selected PER NOTE by the $c0-$ff sequence command (index ->
;     IFM_LO/IFM_HI -> VIFM -> FMP), decoupled from the instrument. ------------
FM_ON     = $182c        ; per-voice: 1 = FM running (3)
FM_IDX    = $182f        ; per-voice: (legacy, unused) (3)
FM_CNT    = $1832        ; per-voice: frames left on current entry (3)
FM_ACC_LO = $1835        ; per-voice: accumulated freq offset lo (3)
FM_ACC_HI = $1838        ; per-voice: accumulated freq offset hi (3)
FM_OFF_LO = $183b        ; per-voice: current entry offset lo (3)
FM_OFF_HI = $183e        ; per-voice: current entry offset hi (3)
vbasenote = $1841        ; per-voice: base note index (note+transpose) for the
                         ; wave-table semitone column; wave_step recomputes
                         ; vfreq = freqtable[vbasenote + col1] each frame (3)
FMP_LO    = $1844        ; per-voice: current FMTAB read pointer lo (3)
FMP_HI    = $1847        ; per-voice: current FMTAB read pointer hi (3)
VIFM_LO   = $184a        ; per-voice: current instrument's FM-start addr lo (3)
VIFM_HI   = $184d        ; per-voice: current instrument's FM-start addr hi (3)
PPTR_LO   = $1850        ; per-voice: current PULSETAB read pointer lo (3)
PPTR_HI   = $1853        ; per-voice: current PULSETAB read pointer hi (3)
VIPUL_LO  = $1856        ; per-voice: current cmd's pulse-program start addr lo (3)
VIPUL_HI  = $1859        ; per-voice: current cmd's pulse-program start addr hi (3)
VWCNT     = $185c        ; per-voice: frames left on current WAVE row (RLE count) (3)
SWTOG     = $185f        ; swing-tempo phase toggle (EOR #$ff per row, mirroring the
                         ; MoN ROM's $E2 at $1134-$1138): negative phase reloads
                         ; TEMPO2 (the SHORT period), positive reloads TEMPO.
                         ; Constant tunes set TEMPO2 = TEMPO so the toggle is inert.
PFREE     = $1860        ; per-voice: pulse free-run stream started (VIFLAGS $08) (3)
VSTEP_LO  = $1863        ; per-voice: freqtable[vbasenote+1]-freqtable[vbasenote] (3)
VSTEP_HI  = $1866        ;   (the note's semitone step, set at pr_note — the unit
                         ;    for SCALED vibrato FM entries) (3)
mul_a     = $1869        ; scaled-entry multiply scratch: scale bits
mul_m     = $186a        ; 24-bit shifted step (3)
mul_p     = $186d        ; 24-bit product (3)
FM_TGT_LO = $1870        ; per-voice SLIDE target offset (freqtable[note+ivl]-vfreq) (3)
FM_TGT_HI = $1873        ;   (3)
FM_SLIDE  = $1876        ; per-voice: 1 = slide active (fm_add clamps at FM_TGT) (3)

        .include "layout.inc"
INSTR_AD    = INSTR + 0*32
INSTR_SR    = INSTR + 1*32
INSTR_FLAGS = INSTR + 2*32   ; flags ($40 = start filter program)
INSTR_FILT  = INSTR + 3*32   ; filter-program start row
INSTR_PULSE = INSTR + 4*32   ; pulse-program start row
INSTR_WAVE  = INSTR + 5*32

; --- Block-2 playback-state region (editor reads these) -------------------
ST_FIRST    = $16cc
ST_LAST     = $1702
; (SF2II writes the SID channel offsets 0,7,14 to $16cc-$16ce, so keep our
;  state bytes clear of that range.)
ST_STATE    = $16d0       ; m_DriverStateAddress: $80 playing / $40 stopped.
                          ; SF2II reads this to drive the play cursor (follow)
                          ; and to detect a self-stop.
ST_TCNT     = $16d1       ; m_TempoCounterAddress: 0 on the frame a new row
                          ; ticks (SF2II advances its follow cursor on 0).
ST_PLAY     = $16d2       ; internal: 1 = playing, 0 = stopped/idle. SF2II calls
                          ; STOP on load + on the stop key, INIT on play, so this
                          ; gates do_play (no playback until the user presses play).
ST_TICK     = $16db

        * = ST_FIRST
        .fill ST_LAST - ST_FIRST + 1, 0

; ==========================================================================
        * = $1000
drv_init:   jmp do_init
drv_play:   jmp do_play
drv_stop:   jmp do_stop

; --- INIT -----------------------------------------------------------------
do_init:
        ldx #$18
ci:     lda #$00
        sta SID,x
        dex
        bpl ci
        ldx #(ST_LAST - ST_FIRST)
cs:     lda #$00
        sta ST_FIRST,x
        dex
        bpl cs
        ldx #$02
iv:     lda #$41
        sta vwf,x
        lda #$00
        sta vhold,x
        sta vtrans,x
        lda #$00
        sta VWI,x                ; wave program starts at row 0
        sta VWCNT,x              ; 0 -> wave_step resolves + loads the row's count
        sta VIWAVE,x
        sta vfreq_lo,x
        sta vfreq_hi,x
        sta VPC,x                ; pulse: VPC=0 -> reload on the first frame
        sta VPLO,x
        sta VPHI,x
        sta VPADL,x
        sta VPADH,x
        sta PFREE,x              ; free-run pulse stream not started
        lda #$fe
        sta VGMASK,x             ; start gated off
        lda #$00
        sta FM_ON,x              ; FM idle until a note triggers
        sta FM_ACC_LO,x
        sta FM_ACC_HI,x
        sta FM_CNT,x
        sta FMP_LO,x
        sta FMP_HI,x
        lda IFM_LO               ; default FM = program 0 (flat) until a cmd selects
        sta VIFM_LO,x
        lda IFM_HI
        sta VIFM_HI,x
        lda IPULSE_LO            ; default pulse = program 0 until a cmd selects
        sta VIPUL_LO,x
        sta PPTR_LO,x            ; point the read pointer at it
        lda IPULSE_HI
        sta VIPUL_HI,x
        sta PPTR_HI,x
        lda #$00
        sta vbasenote,x          ; base note index (set on each note trigger)
        ; orderlist ptr = OL_x ; then load the first pattern
        lda ollo,x
        sta vol_lo,x
        lda olhi,x
        sta vol_hi,x
        jsr next_pattern         ; sets vsp[x] + vtrans[x] from the orderlist
        dex
        bpl iv
        lda #$00                 ; filter program idle until a flag-$40 note
        sta F_ACT
        sta F_MODE
        sta F_CLO
        sta F_CHI
        sta F_CNT
        sta SWTOG                ; swing phase starts at 0 (first row reloads SHORT)
        lda #$01
        sta zp_tcnt
        sta ST_PLAY              ; INIT = play: enable do_play
        lda #$80
        sta ST_STATE             ; report "playing"
.if DIGI_SPIKE
.if DIGI_HYBRID
        lda #<digi_nco_tab       ; nptr -> per-frame lead (incr,ldx,count) table
        sta nptr
        lda #>digi_nco_tab
        sta nptr+1
        lda #<digi_triggers      ; dtp -> drum trigger list
        sta dtp
        lda #>digi_triggers
        sta dtp+1
        ldy #$00
        lda (dtp),y              ; first frame-delta -> countdown
        sta dcdown
        sty dcnt                 ; no active drum yet
        sty dcnt+1
        sty nphase               ; NCO phase = 0
        lda #$ff
        sta pincr                ; force a phase reset on the first lead note
.if DIGI_RLE
        lda (nptr),y             ; RLE: first record's repeat count -> nrep
        sta nrep
        inc nptr                 ; nptr -> record body (incr,nsegs,segs)
        bne diginr0
        inc nptr+1
diginr0:
.endif
.elsif DIGI_NCO
        lda #<digi_nco_tab       ; dtp -> per-frame lead (incr,ldx,count) table
        sta dtp
        lda #>digi_nco_tab
        sta dtp+1
        lda #$00
        sta nphase               ; NCO phase = 0
.else
        lda #<digi_triggers      ; point the trigger walker at the start
        sta dtp
        lda #>digi_triggers
        sta dtp+1
        ldy #$00
        lda (dtp),y              ; first frame-delta -> countdown
        sta dcdown
        sty dcnt                 ; no active sample yet (16-bit count)
        sty dcnt+1
.endif
.endif
        rts

; --- PLAY -----------------------------------------------------------------
;     Runs the player MULTISPEED times per call. SF2II calls do_play once per
;     PAL video frame (50 Hz), but the original is CIA-multispeed (Galway's
;     Wizball = 4 play-calls/frame). Trace data is per-play-call, so to match
;     the real wall-clock speed the driver replays MULTISPEED play-ticks each
;     video frame. MULTISPEED comes from layout.inc (1 = single-speed). --------
do_play:
        lda ST_PLAY              ; idle until SF2II issues play (INIT); STOP clears
        bne dp_go
        rts
dp_go:
        lda #$80
        sta ST_STATE             ; report "playing" to SF2II (drives follow cursor)
        lda #$01
        sta ST_TCNT              ; non-zero unless a row ticks this frame (do_row)
        inc ST_TICK
.if DIGI_SPIKE
        ; Force full master volume ONLY when a SID voice is gated on (so the voices
        ; aren't cut under/after the digi bursts). During the pure-digi intro (all
        ; voices idle) this $0f would plate a full-volume blip in front of each
        ; sawtooth burst and corrupt the digi tone -> skip it; the digi owns $D418.
        lda VGMASK               ; per-voice gate mask: $ff = gated on, $fe = off
        ora VGMASK+1
        ora VGMASK+2
        and #$01                 ; bit 0 set if ANY voice is gated on
        beq dp_novol             ; all idle -> leave $D418 to the digi (clean sawtooth)
.endif
        lda F_MODE               ; filter passband bits (from the filter program)
        ora #$0f                 ; + main volume: keep the gated SID voices at full vol
        sta SID_VOL
dp_novol:
        lda #MULTISPEED
        sta ms_cnt
dp_tick:
        dec zp_tcnt
        bne dp_vib
        jsr do_row               ; row tick: step the sequencer
dp_vib:
        ; filt_prog_step / pulse_step run AFTER do_row so a note's RESET (pr_note
        ; sets F_IDX=VIFILT/F_CNT=0 for the filter, PPTR=VIPUL/VPC=0 for the pulse)
        ; takes effect on the SAME frame as the note — else the cutoff/pulse sweep
        ; lags one frame (audible on the lead's per-note resonant pluck + ramp).
        jsr filt_prog_step       ; global filter program -> $D415/6/7 + mode
        jsr pulse_step           ; per-voice pulse-program -> $D402/3 each tick
        jsr wave_step            ; wave-program -> $D404 + recompute vfreq
        jsr fm_step              ; per-voice freq -> $D400/1 (+ FM accumulate)
        dec ms_cnt
        bne dp_tick              ; next multispeed tick this frame
.if DIGI_SPIKE
        jsr digi_stream          ; interleave: stream the digi drums over the music
.endif
        rts

; --- per-voice wave-program runner (standard 2-col wave table, like Driver 11:
;     col0 = waveform (or $7f jump marker), col1 = signed semitone offset (or,
;     on a $7f row, the jump-target row). ONE row per frame. Each frame: resolve
;     $7f jumps, write $D404 = waveform & gate-mask, and apply col1 as a signed
;     semitone offset to the note (vfreq = freqtable[vbasenote + col1], clamped
;     to [0,$6f]); fm_step then writes vfreq. col1 $00 => no offset. The trace
;     build emits the full per-frame Galway pitch envelope this way — one row
;     per frame with the settled tail looped — keeping the wave table in SF2II's
;     native 2-column format so it renders + edits + PLAYS in stock SF2II. -----
; RLE wave program (MoN): the table stays column-major 256x2, but col1 is now a FRAME
; COUNT (not a semitone -- MoN's pitch is the FM program, so the semitone was always 0).
; A row (waveform, count) holds its waveform for `count` frames before advancing, so a
; long gate-off ($41 x48, $40) packs into ~2 rows instead of 49. $7f rows are jumps
; (col1 = target row) for the sustain loop. Per-voice VWCNT,x = frames left on the row.
; (The old per-frame semitone+drum paths are dropped: MoN never set them.)
wave_step:
        ldx #$02
ws_l:
        lda VWCNT,x
        bne ws_play              ; still holding the current row -> just replay it
        ; --- row expired: step to the next row, resolving $7f jumps, load its count ---
        ldy VWI,x
        lda #$08
        sta ws_grd
ws_read:
        lda WAVE,y               ; col0 = waveform (or $7f jump marker)
        cmp #$7f
        bne ws_got
        lda WAVE+256,y           ; $7f: col1 = jump target row
        tay
        dec ws_grd
        bne ws_read
        tya                      ; $7f-loop guard tripped -> park + silence
        sta VWI,x                ; (STY abs,x is invalid -> TYA/STA)
        lda #$01
        sta VWCNT,x
        lda #$00
        ldy sidbase,x
        sta SID+4,y
        jmp ws_next
ws_got:
        tya
        sta VWI,x                ; resolved row (never $7f); Y still = the row
        lda WAVE+256,y           ; col1 = frame count for this row
        sta VWCNT,x
ws_play:
        lda vbasenote,x          ; MoN: semitone 0 -> vfreq = freqtable[vbasenote]
        asl                      ;   (FM adds the per-frame pitch offset afterwards)
        tay
        lda freqtable,y
        sta vfreq_lo,x
        lda freqtable+1,y
        sta vfreq_hi,x
        ldy VWI,x                ; waveform col0 -> $D404 (masked by the gate)
        lda WAVE,y
        and VGMASK,x
        ldy sidbase,x
        sta SID+4,y
        dec VWCNT,x              ; consume one frame; on expiry step to the next row
        bne ws_next
        inc VWI,x
ws_next:
        dex
        bmi ws_done              ; (bpl ws_l now out of branch range)
        jmp ws_l
ws_done:
        rts

; --- per-voice pulse-program runner: walk the standard pulse table (set/add/
;     jump), applying the per-frame add and writing $D402/3 each frame. --------
pulse_step:
        ldx #$02
pl_l:
        lda VPC,x
        bne pl_apply             ; still on current row -> just apply the add
        ; row expired -> load the next PULSETAB entry via the 16-bit pointer
        lda PPTR_LO,x
        sta pptr
        lda PPTR_HI,x
        sta pptr+1
        ldy #$00
        lda (pptr),y             ; byte0 = cmd nibble | width-hi nibble (or $7f)
        cmp #$7f
        bne pl_decode
        ; $7f = freeze: add 0, hold, do NOT advance the pointer
        lda #$00
        sta VPADL,x
        sta VPADH,x
        lda #$ff
        sta VPC,x
        jmp pl_apply
pl_decode:
        sta tmpf                 ; byte0
        ldy #$02
        lda (pptr),y             ; byte2 = frame count
        sta VPC,x
        lda PPTR_LO,x            ; advance pointer by 3 bytes (row-major)
        clc
        adc #$03
        sta PPTR_LO,x
        bcc pl_b1
        inc PPTR_HI,x
pl_b1:
        ldy #$01
        lda (pptr),y             ; byte1 = width lo
        sta tmpf+1
        lda tmpf
        bmi pl_set               ; bit7 set -> 8X (set width)
        and #$0f                 ; 0X (add): VPAD = (byte0&0f):byte1
        sta VPADH,x
        lda tmpf+1
        sta VPADL,x
        jmp pl_apply
pl_set:
        lda tmpf                 ; 8X: pulse = (byte0&0f):byte1, add = 0
        and #$0f
        sta VPHI,x
        lda tmpf+1
        sta VPLO,x
        lda #$00
        sta VPADL,x
        sta VPADH,x
pl_apply:
        ; SEEK voices (VIFLAGS $10) HOLD the pulse on the note's LAST frame -- the
        ; frame before do_row advances (zp_tcnt==1) of the note's last row (vhold==0).
        ; The real player ramps the SEEK only while the note still sustains; tied
        ; notes (vhold>0) ramp through the row boundary. (PWM voices ramp every frame.)
        lda VIFLAGS,x
        and #$10
        beq pl_add
        lda zp_tcnt
        cmp #$01
        bne pl_add
        lda vhold,x
        bne pl_add
        jmp pl_consume           ; SEEK last frame -> hold (skip the add)
pl_add:
        lda VPLO,x               ; pulse += add (12-bit)
        clc
        adc VPADL,x
        sta VPLO,x
        lda VPHI,x
        adc VPADH,x
        and #$0f
        sta VPHI,x
pl_consume:
        lda VPC,x                ; consume a frame
        beq pl_wr
        dec VPC,x
pl_wr:
        ldy sidbase,x
        lda VPLO,x
        sta SID+2,y
        lda VPHI,x
        sta SID+3,y
        dex
        bmi pl_done              ; (bpl pl_l would branch too far -> use jmp)
        jmp pl_l
pl_done:
        rts

; --- global filter-program runner: walk the standard filter table (set passband/
;     cutoff/res/bitmask, add-to-cutoff, jump), writing $D415/6 (cutoff), $D417
;     (res+routing) and F_MODE (passband -> $D418 high nibble). Restarted by a
;     flag-$40 note (see pr_note). Cutoff held 16-bit, hi byte -> $D416. -------
filt_prog_step:
        lda F_ACT
        bne fp_run
        rts
fp_run:
        lda F_CNT
        beq fp_load              ; F_CNT==0 -> load next row
        jmp fp_apply             ; else just apply the per-frame add
fp_load:
        lda #$08
        sta ws_grd
        ldy F_IDX
fp_read:
        lda FILTER,y             ; byte0
        cmp #$7f
        bne fp_dec
        sty tmpf                 ; jump row: target = byte2
        lda FILTER+512,y
        cmp tmpf
        beq fp_freeze
        sta F_IDX
        tay
        dec ws_grd
        bne fp_read
fp_freeze:
        lda #$00
        sta F_ADLO
        sta F_ADHI
        lda #$ff
        sta F_CNT
        jmp fp_apply
fp_dec:
        lda FILTER,y             ; reload byte0; bit7 distinguishes set ($9x) from add
        bmi fp_set               ; ($0x) — CMP-bug-safe (SF2II miscomputes `cmp #$90`
                                 ; vs $0x add rows, >$7f apart; mirror pulse_step bmi)
        ; --- 0X add-to-cutoff: F_AD = ((byte0&f):byte1) << 4 ---
        and #$0f
        sta tmpf+1               ; XXX hi nibble
        lda FILTER+256,y         ; byte1 = XXX low 8 bits
        pha
        asl
        asl
        asl
        asl
        sta F_ADLO               ; byte1 << 4
        pla
        lsr
        lsr
        lsr
        lsr                      ; byte1 >> 4
        sta tmpf
        lda tmpf+1
        asl
        asl
        asl
        asl                      ; (XXX hi) << 4
        ora tmpf
        sta F_ADHI
        lda FILTER+512,y         ; byte2 = frames
        sta F_CNT
        iny
        tya
        sta F_IDX
        jmp fp_apply
fp_set:
        ; --- 9Y YY RB set-filter: passband X, cutoff Y:byte1, res:bitmask byte2 ---
        sta tmpf                 ; byte0 = X:Y
        lsr
        lsr
        lsr
        lsr                      ; X (passband)
        and #$07
        asl
        asl
        asl
        asl                      ; (X&7) << 4 = SID mode bits
        sta F_MODE
        lda tmpf
        and #$0f                 ; Y = cutoff hi nibble
        asl
        asl
        asl
        asl                      ; Y << 4
        sta tmpf+1
        lda FILTER+256,y         ; byte1 = cutoff low 8 bits
        pha
        lsr
        lsr
        lsr
        lsr                      ; byte1 >> 4
        ora tmpf+1
        sta F_CHI                ; cutoff hi -> $D416
        pla
        asl
        asl
        asl
        asl
        sta F_CLO
        lda FILTER+512,y         ; byte2 = R:B -> res_control
        sta $d417
        lda #$00
        sta F_ADLO
        sta F_ADHI
        lda #$01
        sta F_CNT
        iny
        tya
        sta F_IDX
fp_apply:
        lda F_CLO                ; cutoff += add (16-bit)
        clc
        adc F_ADLO
        sta F_CLO
        lda F_CHI
        adc F_ADHI
        sta F_CHI
        lda F_CNT
        beq fp_write
        dec F_CNT
fp_write:
        lda F_CLO
        sta $d415
        lda F_CHI
        sta $d416
        rts

; --- per-voice FM offset-list runner (trace-driven): writes $D400/1 = vfreq +
;     FM_ACC every frame. For FM-on voices, walk FMTAB from FM_IDX, accumulating
;     the current signed offset into FM_ACC for its duration; dur 0 = freeze. The
;     offset list is the real per-frame pitch envelope captured from the player. -
fm_step:
        ldx #$02
fm_l:
        lda FM_ON,x
        bne fm_run
        jmp fm_write             ; FM off -> freq = vfreq (FM_ACC stays 0)
fm_run:
        lda #$10                 ; per-voice runaway guard for chained $7f loop
        sta ws_grd               ; entries (reuses the wave_step scratch byte)
        lda FM_CNT,x
        beq fm_load              ; current entry expired -> load next
        jmp fm_add
; --- FM entry dispatch on byte2 (all forms 3 bytes: byte0, byte1, byte2):
;       $00       freeze: offset 0, hold forever (unchanged)
;       $01-$7e   Hz-delta run: FM_OFF = byte0/byte1 signed, applied byte2 frames
;                 (the emitter caps RLE runs at 126 so byte2 stays < $7f)
;       $7f       LOOP: byte0 = entry index; FMP = VIFM + byte0*3, re-dispatch
;       $80-$ff   SEMITONE hold (structural arps): S = byte0 signed semitones,
;                 dur = byte2 & $7f; FM_ACC = freqtable[(vbasenote+S)&$7f] - vfreq
;                 (pitch-INDEPENDENT — one chord-arp program serves every note).
;     Dispatch is bit-test first (bmi), then cmp #$7f only with A in $01-$7f —
;     SF2II CMP-carry-safe. ---
fm_load:
        lda FMP_LO,x             ; point fmptr at the current row-major entry
        sta fmptr
        lda FMP_HI,x
        sta fmptr+1
        ldy #$02
        lda (fmptr),y            ; byte 2 = entry type/dur
        bne fm_notfrz
fm_freeze:
        lda #$00                 ; freeze: offset 0, hold, do not advance
        sta FM_OFF_LO,x
        sta FM_OFF_HI,x
        lda #$ff
        sta FM_CNT,x
        jmp fm_add
fm_notfrz:
        bmi fm_semi              ; bit7 -> semitone entry
        cmp #$7f                 ; A is $01-$7f here (CMP-carry-safe)
        beq fm_loopent
        sta FM_CNT,x             ; --- Hz-delta run (original form) ---
        ldy #$01
        lda (fmptr),y            ; byte 1 = offset hi — $40/$41 marks a SCALED
        and #$fe                 ;   (pitch-proportional vibrato) entry:
        eor #$40                 ;   offset = +-(VSTEP * byte0) >> 8
        bne fm_plainhz           ;   (eor test — SF2II CMP-carry-safe)
        jmp fm_scaled            ;   (mul block lives past fm_done: branch range)
fm_plainhz:
        lda (fmptr),y
        sta FM_OFF_HI,x
        ldy #$00
        lda (fmptr),y            ; byte 0 = offset lo
        sta FM_OFF_LO,x
        jmp fm_adv3
fm_semi:
        and #$7f                 ; dur (>= 1)
        sta FM_CNT,x
        ldy #$00
        lda (fmptr),y            ; byte 0 = signed semitone offset / slide interval
        clc
        adc vbasenote,x
        and #$7f
        asl                      ; freqtable is interleaved lo/hi (note*2)
        tay
        sec
        lda freqtable,y          ; offset = freqtable[note+S] - vfreq
        sbc vfreq_lo,x
        sta FM_TGT_LO,x
        lda freqtable+1,y
        sbc vfreq_hi,x
        sta FM_TGT_HI,x
        ldy #$01
        lda (fmptr),y            ; byte 1: 0 = instant semitone set (arps);
        beq fm_inst              ;   1-31 = SLIDE speed (rate = 7 << (speed-1))
        jmp fm_slset             ; slide setup lives past fm_done (branch range)
fm_inst:
        lda FM_TGT_LO,x          ; instant: FM_ACC = the offset, no per-frame add
        sta FM_ACC_LO,x
        lda FM_TGT_HI,x
        sta FM_ACC_HI,x
        lda #$00
        sta FM_OFF_LO,x
        sta FM_OFF_HI,x
fm_adv3:
        lda FMP_LO,x             ; advance pointer by 3 bytes
        clc
        adc #$03
        sta FMP_LO,x
        bcc fm_add
        inc FMP_HI,x
        jmp fm_add
fm_loopent:
        dec ws_grd               ; degenerate loop chain -> freeze this frame
        bne fm_loopok            ; (near-branch + jmp: fm_freeze is out of range)
        jmp fm_freeze
fm_loopok:
        ldy #$00
        lda (fmptr),y            ; byte 0 = loop-back entry index
        sta tmpf
        asl                      ; idx*3 (idx <= 84, no carry)
        clc
        adc tmpf
        clc
        adc VIFM_LO,x            ; FMP = program start + idx*3
        sta FMP_LO,x
        lda VIFM_HI,x
        adc #$00
        sta FMP_HI,x
        jmp fm_load              ; re-dispatch at the loop target
fm_add:
        lda FM_ACC_LO,x          ; FM_ACC += signed offset
        clc
        adc FM_OFF_LO,x
        sta FM_ACC_LO,x
        lda FM_ACC_HI,x
        adc FM_OFF_HI,x
        sta FM_ACC_HI,x
        lda FM_SLIDE,x           ; active slide: clamp at the target
        beq fm_nosl
        sec                      ; D = TGT - ACC
        lda FM_TGT_LO,x
        sbc FM_ACC_LO,x
        sta tmpf
        lda FM_TGT_HI,x
        sbc FM_ACC_HI,x
        sta tmpf+1
        ora tmpf
        beq fm_clamp             ; arrived exactly
        lda tmpf+1
        eor FM_OFF_HI,x          ; sign(D) != sign(OFF) -> overshot
        bpl fm_nosl
fm_clamp:
        lda FM_TGT_LO,x
        sta FM_ACC_LO,x
        lda FM_TGT_HI,x
        sta FM_ACC_HI,x
        lda #$00
        sta FM_OFF_LO,x
        sta FM_OFF_HI,x
        sta FM_SLIDE,x
fm_nosl:
        lda FM_CNT,x
        beq fm_write
        dec FM_CNT,x
fm_write:
        ldy sidbase,x            ; freq = vfreq + FM_ACC
        lda vfreq_lo,x
        clc
        adc FM_ACC_LO,x
        sta SID+0,y
        lda vfreq_hi,x
        adc FM_ACC_HI,x
        sta SID+1,y
        dex
        bmi fm_done
        jmp fm_l
fm_done:
        rts
do_row:
        lda #$00
        sta ST_TCNT              ; a new row ticked this frame (SF2II follow cursor++)
        ; swing-tempo reload (MoN ROM $1128-$114D): alternate TEMPO2 (short) and
        ; TEMPO (long) per row, short phase first — matches the ROM's $E2 toggle
        ; starting at 0. Constant tunes have TEMPO2 == TEMPO. (bmi = bit test,
        ; SF2II CMP-carry-safe.)
        lda SWTOG
        eor #$ff
        sta SWTOG
        bmi dr_short
        lda #TEMPO
        jmp dr_setcnt
dr_short:
        lda #TEMPO2
dr_setcnt:
        sta zp_tcnt
        ldx #$00
vloop:
        lda vhold,x
        beq vparse
        dec vhold,x
        jmp vnext
vparse:
        lda sidbase,x
        sta sidoff
        lda vsp_lo,x
        sta wptr
        lda vsp_hi,x
        sta wptr+1
        lda #$20
        sta zp_guard
        lda #$00
        sta pending_dur
        jsr parse_one
        lda wptr
        sta vsp_lo,x
        lda wptr+1
        sta vsp_hi,x
        lda pending_dur
        sta vhold,x
vnext:
        inx
        cpx #$03
        bne vloop
        rts

; --- parse one packed event for voice X (sidoff/wptr set) -----------------
parse_one:
pr_read:
        dec zp_guard
        bne pr_go
        rts                      ; guard expired -> bail this row (suspends)
pr_go:
        ldy #$00
        lda (wptr),y
        cmp #$7f
        bne pr_cmd
        ; end of sequence -> advance the orderlist to the next pattern
        jsr next_pattern
        lda vsp_lo,x
        sta wptr
        lda vsp_hi,x
        sta wptr+1
        jmp pr_read
pr_cmd:
        ; Classify by the HIGH BIT first ($00-$7f = note, $80+ = cmd/instr/dur).
        ; SF2II's 6510 emulator computes CMP's carry from bit7 of (A-operand)
        ; rather than (A>=operand), so a wide compare like `cmp #$c0` mis-sets
        ; carry when the operand is far above A (e.g. note $19 vs $c0) and the
        ; note is misread as a command -> silent playback. Splitting on $80
        ; first keeps every compare within +-$7f, where its carry is correct.
        cmp #$80
        bcc pr_note              ; $00-$7f -> note
        cmp #$c0
        bcs pr_setprog           ; $c0-$ff -> set per-note synth program (slide+pulse)
        cmp #$a0
        bcs pr_setinst           ; $a0-$bf -> set instrument
        sta tieflag              ; $80-$9f -> duration; bit $10 = tie marker
        and #$0f
        sta pending_dur
        lda tieflag
        and #$10                 ; isolate tie bit -> tieflag (0 or $10)
        sta tieflag
        jsr advw
        jmp pr_read
pr_setprog:
        ; $c0-$ff: select this voice's PER-NOTE synth program (a bundle of FM
        ; slide + pulse-width envelope), decoupled from the instrument. index =
        ; byte & $3f selects both the FM-start pointer (IFM) and the pulse-program
        ; start addr (IPULSE_LO/HI); pr_note restarts both. Lets a long song
        ; carry many distinct slide+pulse shapes without inflating the <=32
        ; instrument table (timbre = instrument; slide+pulse = this command).
        and #$3f
        tay
        lda IFM_LO,y
        sta VIFM_LO,x
        lda IFM_HI,y
        sta VIFM_HI,x
        lda IPULSE_LO,y
        sta VIPUL_LO,x
        lda IPULSE_HI,y
        sta VIPUL_HI,x
        jsr advw
        jmp pr_read
pr_setinst:
        and #$1f
        jsr set_instr_v
        jsr advw
        jmp pr_read
pr_note:
        cmp #$00
        bne pn_not_off
        lda #$fe                 ; gate off: wave_step keeps writing gate-off
        sta VGMASK,x
        lda vwf,x
        and #$fe
        ldy sidoff
        sta SID+4,y
        jmp advw
pn_adv:
        jmp advw                 ; trampoline (advw now out of branch range)
pn_not_off:
        cmp #$7e
        beq pn_adv
        cmp #$70
        bcs pn_adv
        clc                      ; apply transpose
        adc vtrans,x
        sta vbasenote,x          ; base note index for the wave-table semitone col
        asl
        tay
        lda freqtable,y
        sta tmpf
        lda freqtable+1,y
        sta tmpf+1
        ; VSTEP = the note's semitone step (freqtable[n+1] - freqtable[n]) — the
        ; unit for SCALED (pitch-proportional vibrato) FM entries
        sec
        lda freqtable+2,y
        sbc tmpf
        sta VSTEP_LO,x
        lda freqtable+3,y
        sbc tmpf+1
        sta VSTEP_HI,x
        lda tmpf                 ; remember the base freq for vibrato
        sta vfreq_lo,x
        lda tmpf+1
        sta vfreq_hi,x
        lda #$00
        sta vib_phase,x
        lda #VIBDLY
        sta vib_delay,x
        ldy sidoff
        lda tmpf
        sta SID+0,y
        lda tmpf+1
        sta SID+1,y
        lda tieflag              ; TIE -> change pitch only: no gate re-attack, and
        bne pn_tied              ; leave the pulse program free-running (legato)
        lda vwf,x                ; retrigger: gate off then on
        and #$fe
        sta SID+4,y
        lda vwf,x
        ora #$01
        sta SID+4,y
        ; pulse FREE-RUN (VIFLAGS $08): MoN sweeps whose phase never resets are
        ; emitted as ONE per-voice stream program — after the first flagged note
        ; starts it, later note-ons keep PPTR/VPC (the stream runs across notes).
        lda VIFLAGS,x
        and #$08
        beq pn_prst
        lda PFREE,x
        bne pn_noprst            ; stream already running -> keep the phase
        lda #$01
        sta PFREE,x              ; first flagged note: start the stream normally
pn_prst:
        lda VIPUL_LO,x           ; restart the pulse program too (16-bit pointer)
        sta PPTR_LO,x
        lda VIPUL_HI,x
        sta PPTR_HI,x
        lda #$00
        sta VPC,x                ; force reload on the next frame
pn_noprst:
pn_tied:
        lda VIWAVE,x             ; restart the wave program at the instrument's row
        sta VWI,x
        lda #$00
        sta VWCNT,x              ; 0 -> wave_step resolves the start row + loads count
        lda #$ff
        sta VGMASK,x             ; gate on (wave_step keeps the gate asserted)
        ; (re)start the FM offset-list at this note's FM program (set per note by
        ; the $c0-$ff command). The trigger frame shows the BASE pitch (FM_ACC=0);
        ; the first FM delta is applied the NEXT frame — matching the real SID,
        ; whose frequency at the onset frame is the base note before any slide
        ; accumulates. (FM_CNT=1 + FM_OFF=0 holds zero for this frame, then
        ; FM_CNT hits 0 next frame and loads entry 0.) Applying the first delta on
        ; the trigger frame put every FM-modulated voice 1 frame ahead of the
        ; trace (audible phase-shift on the lead + arps).
        lda VIFM_LO,x
        sta FMP_LO,x
        lda VIFM_HI,x
        sta FMP_HI,x
        lda #$00
        sta FM_ACC_LO,x
        sta FM_ACC_HI,x
        sta FM_OFF_LO,x          ; no offset on the trigger frame
        sta FM_OFF_HI,x
        sta FM_SLIDE,x           ; cancel any running slide
        lda #$01
        sta FM_CNT,x             ; hold base this frame; load entry 0 next frame
        sta FM_ON,x
        lda VIFLAGS,x            ; flag $40 -> (re)start the filter program
        and #$40
        beq pn_nofilt
        lda VIFILT,x
        sta F_IDX
        lda #$00
        sta F_CNT                ; force reload next frame
        lda #$01
        sta F_ACT
pn_nofilt:
        jmp advw

pr_ret:
        rts

advw:
        inc wptr
        bne advw_done
        inc wptr+1
advw_done:
        rts

; --- advance voice X's orderlist to the next pattern: set vsp[x]+vtrans[x] --
next_pattern:
        lda #$20
        sta np_guard
        lda vol_lo,x             ; wptr = orderlist read pointer
        sta wptr
        lda vol_hi,x
        sta wptr+1
np_read:
        dec np_guard
        beq np_ret
        ldy #$00
        lda (wptr),y
        cmp #$ff
        beq np_ff
        cmp #$fe
        beq np_fe
        cmp #$80
        bcc np_seq
        ; transposition byte: offset = (val & $7f) - $20
        and #$7f
        sec
        sbc #$20
        sta vtrans,x
        jsr ol_adv
        jmp np_read
np_seq:
        ; sequence index -> vsp[x] from the seq pointer table
        tay
        lda SEQPTRLO,y
        sta vsp_lo,x
        lda SEQPTRHI,y
        sta vsp_hi,x
        jsr ol_adv               ; step past the index
        lda wptr                 ; save orderlist pointer back
        sta vol_lo,x
        lda wptr+1
        sta vol_hi,x
np_ret:
        rts
np_fe:
        ; end, no loop -> restart this voice's orderlist
        lda ollo,x
        sta wptr
        lda olhi,x
        sta wptr+1
        jmp np_read
np_ff:
        ; end with loop -> orderlist start + loop index (byte after $FF)
        ldy #$01
        lda (wptr),y
        clc
        adc ollo,x
        sta wptr
        lda olhi,x
        adc #$00
        sta wptr+1
        jmp np_read

; advance the working orderlist pointer by 1
ol_adv:
        inc wptr
        bne ol_adv_done
        inc wptr+1
ol_adv_done:
        rts

; set instrument for voice X: A = index
set_instr_v:
        ; Neither FM nor pulse is tied to the instrument any more — both are
        ; selected per note by the $c0-$ff command (see pr_setprog). The
        ; instrument sets only timbre: AD/SR/flags/filter/waveform.
        tay
        lda INSTR_AD,y
        sta tmpf
        lda INSTR_SR,y
        sta tmpf+1
        lda INSTR_FLAGS,y        ; flags ($40 = start filter program)
        sta VIFLAGS,x
        lda INSTR_FILT,y         ; filter-program start row
        sta VIFILT,x
        ; MoN: pulse is PER-COMMAND (the $c0-$ff bundle), NOT per-instrument. Do NOT
        ; set VIPUL here — set_instr runs AFTER the command in token order, so writing
        ; VIPUL would clobber the note's bundle pulse program. The command owns both
        ; FM and pulse; the instrument owns only timbre (AD/SR/flags/filter/waveform).
        ; (Y is still the instrument index from the top of set_instr_v.)
        lda INSTR_WAVE,y
        sta VIWAVE,x             ; instrument's wave-program start row
        tay
        lda WAVE,y
        sta vwf,x                ; first waveform (for pr_note's gate toggle)
        ldy sidoff
        lda tmpf
        sta SID+5,y
        lda tmpf+1
        sta SID+6,y
        rts

; --- STOP -----------------------------------------------------------------
do_stop:
        lda #$00
        sta ST_PLAY              ; STOP: gate do_play off (silent, no advance)
        lda #$40
        sta ST_STATE             ; report "stopped"
        ldx #$18
cz:     lda #$00
        sta SID,x
        dex
        bpl cz
        rts

.if DIGI_SPIKE
; --- DIGI ENGINE (milestone 2): trigger-driven $D418 sample player ----------
; Walks digi_triggers (frame-delta, sample-id) and streams the active sample's
; 4-bit nibbles to $D418 from do_play (proven to render in stock SF2II). One
; tune's drums/voice play on their real rhythm. (No music yet — digi-only test.)
digi_stream:                     ; called AFTER the music body each frame
.if DIGI_HYBRID
; --- HYBRID engine: NCO sawtooth lead + PCM drum samples on one $D418 channel.
;     Each frame: advance the lead pointer (keep the melody time-aligned), service
;     the drum trigger countdown, then EITHER stream the active drum sample (it
;     ducks the lead, as the single channel does in the original) OR run the NCO. ---
.if DIGI_SWEEP
        ldy #$00
        lda (nptr),y             ; byte 0: nibble increment (raw signed step, mod-16 add)
        sta nincr
        cmp pincr                ; note onset (step changed)? -> reset accumulator to 0 so
        beq pnsame               ; the first write == step, anchoring ABSOLUTE levels (a
        sta pincr                ; square step-8 tone -> [8,0,8,0] not a drifted [14,6,..]).
        lda #$00                 ; held notes (step unchanged) keep accumulating across frames.
        sta nphase
pnsame:
        iny
        lda (nptr),y             ; byte 1: gap-sweep segment count (0 = rest/drum)
        sta nsegs
        ; nptr is NOT advanced here -- the seg walk reads from it; advanced after render
        ; (hbswadv) by 2 + 2*nsegs, on BOTH the lead and drum paths.
.else
        ldy #$00
        lda (nptr),y             ; byte 0: phase increment (step<<4)
        sta nincr
        iny
        lda (nptr),y             ; byte 1: write gap (delay loop count; small = fast)
        sta nldx
        iny
        lda (nptr),y             ; byte 2: lead write count this frame (0 = rest/drum)
        sta ncnt
        lda nptr                 ; advance lead table pointer by 3 (16-bit) every frame
        clc
        adc #$03
        sta nptr
        bcc hb0
        inc nptr+1
.endif
hb0:    lda dcdown
        beq hbfire               ; countdown elapsed -> fire next trigger(s)
        dec dcdown
        jmp hbrender
hbfire: lda #$10
        sta dfg                  ; anti-runaway: cap chained (delta-0) fires/frame
hbfl:   dec dfg
        beq hbpark
        ldy #$01
        lda (dtp),y              ; sample-id
        cmp #$ff
        beq hbpark               ; end marker
        cmp #$fe
        beq hbadv                ; gap filler -> just advance
        tax
        lda digi_off_lo,x        ; start a drum sample (bank ptr + 16-bit length)
        sta dbp
        lda digi_off_hi,x
        sta dbp+1
        lda digi_len_lo,x
        sta dcnt
        lda digi_len_hi,x
        sta dcnt+1
hbadv:  lda dtp                  ; trigger pointer += 2
        clc
        adc #$02
        sta dtp
        bcc hbnc
        inc dtp+1
hbnc:   ldy #$00
        lda (dtp),y              ; next frame-delta
        sta dcdown
        beq hbfl                 ; delta 0 -> another hit this same frame
        dec dcdown               ; consume THIS (fire) frame so delta N fires exactly
        jmp hbrender             ; N frames later, not N+1 (else a dense beat drifts)
hbpark: lda #$ff
        sta dcdown               ; park: no further triggers
hbrender:
        lda dcnt                 ; drum sample active? (16-bit count)
        ora dcnt+1
        bne hbpcm
.if DIGI_SWEEP
        ; --- no drum -> gap-SWEEP lead: walk nsegs (gap,runlen) segments, reproducing
        ;     the source's intra-frame gap sweep (32->39->53...) so reSID renders the
        ;     same TIMBRE, not just the right pitch. incr,nsegs were read at frame top. ---
        lda nsegs
        beq hbswadv              ; rest frame -> no lead, just advance the pointer
        sta segc
        ldy #$02                 ; skip [incr][nsegs] -> first segment record
hbseg:  lda (nptr),y             ; segment delay (ldx -> write gap)
        sta nldx
        iny
        lda (nptr),y             ; segment run length (writes at this gap)
        sta ncnt
        iny                      ; Y -> next segment (the write loop preserves Y)
hbsw:   lda nphase
        clc
        adc nincr                ; nibble += raw step
        and #$0f                 ; 4-bit accumulator -> sawtooth output 0..15
        sta nphase
        sta SID_VOL
        ldx nldx
hbswd:  dex
        bne hbswd
        dec ncnt
        bne hbsw
        dec segc
        bne hbseg
hbswadv:
.if DIGI_RLE
        dec nrep                 ; hold this record for `rep` frames (RLE)
        bne hbswok               ; still repeating -> keep nptr at the current body
        ; repeat exhausted -> advance past body, then load next record's [rep] + body
        lda nsegs
        asl a
        clc
        adc #$02
        adc nptr
        sta nptr
        bcc hbsw_nr
        inc nptr+1
hbsw_nr:
        ldy #$00
        lda (nptr),y             ; next record's repeat count
        sta nrep
        inc nptr                 ; nptr -> next record body
        bne hbswok
        inc nptr+1
.else
        lda nsegs                ; advance nptr += 2 + 2*nsegs (to next frame's record)
        asl a                    ; nsegs < 128 -> carry stays clear
        clc
        adc #$02
        adc nptr                 ; carry clear (2*nsegs+2 < 256)
        sta nptr
        bcc hbswok
        inc nptr+1
.endif
hbswok: rts
.else
        ; --- no drum -> tight NCO sawtooth lead (fast write rate) ---
        lda ncnt
        bne hbnloop
        rts                      ; count 0 = rest/drum frame -> leave $D418 to the music
hbnloop:
        lda nphase
        clc
        adc nincr                ; phase += step<<4
        sta nphase
        lsr a
        lsr a
        lsr a
        lsr a                    ; high nibble = sawtooth output 0..15
        sta SID_VOL
        ldx nldx                 ; small delay -> fast write gap (matches the source)
hbnd:   dex
        bne hbnd
        dec ncnt
        bne hbnloop
        rts
.endif
        ; --- drum active -> stream PCM nibbles (ducks the lead) ---
        ; DRUM_WPF nibbles this call at a DRUM_GAP_LDX-tuned gap, both measured from
        ; the source so the drum plays at its REAL pitch/rate (was a fixed ~101-cyc
        ; gap that ran the drums 0.59x too slow/low and stretched them a frame long).
hbpcm:  lda #DRUM_WPF            ; drum $D418 writes this call (source rate)
        sta dwc
hbpl:   lda dcnt
        ora dcnt+1
        beq hbpdone              ; sample exhausted mid-frame -> stop (lead resumes)
        ldy #$00
        lda (dbp),y              ; next 4-bit PCM nibble
        sta SID_VOL
        inc dbp                  ; advance sample read pointer (16-bit)
        bne hbpd1
        inc dbp+1
hbpd1:  lda dcnt                 ; dec 16-bit remaining count
        bne hbpd2
        dec dcnt+1
hbpd2:  dec dcnt
        ldx #DRUM_GAP_LDX        ; gap tuned to the source $D418 spacing (the pitch)
hbpgd:  dex
        bne hbpgd
        dec dwc
        bne hbpl
hbpdone:
.if DIGI_SWEEP
        jmp hbswadv              ; drum frame still advances the lead pointer (alignment)
.else
        rts
.endif
.elsif DIGI_NCO
; --- tight NCO lead: each frame reads (incr, gap, count) and regenerates a 4-bit
;     sawtooth (phase += incr per write, output high nibble) at the source's FAST
;     write gap -> reSID renders the right (smoothed) pitch. 3 B/frame table. ---
        ldy #$00
        lda (dtp),y              ; byte 0: phase increment (step<<4)
        sta nincr
        iny
        lda (dtp),y              ; byte 1: write gap (delay loop count; small = fast)
        sta nldx
        iny
        lda (dtp),y              ; byte 2: write count this frame (0 = rest)
        sta ncnt
        lda dtp                  ; advance lead table pointer by 3 (16-bit)
        clc
        adc #$03
        sta dtp
        bcc ni0
        inc dtp+1
ni0:    lda ncnt
        bne nloop                ; count 0 = rest -> leave $D418 to the music ($0f)
        rts
nloop:  lda nphase
        clc
        adc nincr                ; phase += step<<4
        sta nphase
        lsr a
        lsr a
        lsr a
        lsr a                    ; high nibble = sawtooth output 0..15
        sta SID_VOL
        ldx nldx
nd:     dex
        bne nd
        dec ncnt
        bne nloop
        rts
.else
        lda #$10
        sta dfg                  ; cap chained fires/frame (anti-runaway guard)
        lda dcdown
        bne ddec                 ; still counting down to the next trigger
df:     dec dfg
        beq dpark                ; guard tripped -> stop firing this frame
        ldy #$01
        lda (dtp),y              ; sample-id
        cmp #$ff
        beq dpark                ; end marker -> no more triggers
        cmp #$fe
        beq dadv                 ; no-op (gap filler) -> just advance
        tax
        lda digi_off_lo,x        ; load the sample: bank pointer + length
        sta dbp
        lda digi_off_hi,x
        sta dbp+1
        lda digi_len_lo,x        ; 16-bit length (whole drums can exceed 255)
        sta dcnt
        lda digi_len_hi,x
        sta dcnt+1
dadv:   lda dtp                  ; trigger pointer += 2
        clc
        adc #$02
        sta dtp
        bcc dnc
        inc dtp+1
dnc:    ldy #$00
        lda (dtp),y              ; next frame-delta
        sta dcdown
        beq df                   ; delta 0 -> another hit this same frame
        jmp dstr
dpark:  lda #$ff
        sta dcdown               ; park: no further triggers
        jmp dstr
ddec:   dec dcdown
dstr:   lda #128                 ; $D418 writes/call (fit music+digi under the cap at
        sta dwc                  ; the 9.75 kHz gap; short drums play whole in 1 frame)
dsl:    lda dcnt                 ; active sample remaining? (16-bit)
        ora dcnt+1
        beq dsil
        ldy #$00
        lda (dbp),y              ; next 4-bit PCM nibble
        sta SID_VOL
        inc dbp                  ; advance sample read pointer (16-bit)
        bne dnp
        inc dbp+1
dnp:    lda dcnt                 ; dec 16-bit remaining count
        bne dnd
        dec dcnt+1
dnd:    dec dcnt
        jmp ddl
dsil:   lda #$0f                 ; between drums -> FULL volume (the music is heard;
        sta SID_VOL              ; the digi modulates the master volume, like the orig)
ddl:    ldx #$0a                 ; ~101-cycle gap = 9.75 kHz (the ORIGINAL digi rate;
ddd:    dex                      ; the gap, NOT writes/sec, sets the sample PITCH)
        bne ddd
        dec dwc
        bne dsl
        rts
.endif
.endif

; SID voice register offsets
sidbase:
        .byte $00, $07, $0e
; per-voice filter-routing bit (AND with FILT_ROUTE -> is this voice filtered?)
frbits:
        .byte $01, $02, $04
; per-voice orderlist start addresses (from the layout)
ollo:
        .byte <OL0, <OL1, <OL2
olhi:
        .byte >OL0, >OL1, >OL2

; Pin the note->freq table ABOVE the playback-state region ($16cc-$1702) so it
; can never collide with it (SF2II reads/writes that state every frame; an
; overlapping freqtable would be corrupted -> crash). The gap $1703-$1A00 (edit
; base) is free. Routines live $1000-~$1623, well below the state region.
        * = $1710
freqtable:
        .include "freqtable.inc"

; Out-of-line FM entry handlers (SCALED vibrato + SLIDE setup): placed in
; the free window between the driver scratch ($1800-$187f) and the edit
; area ($1A00) — the main code bank was overflowing into SF2II's pinned
; playback-state region ($16cc-$1702).
        * = $1880
; SCALED FM entry (out-of-line for branch range): offset = +-(VSTEP * byte0) >> 8
; — a pitch-proportional vibrato leg. 24-bit shift-add multiply, ~200 cycles,
; runs only when an entry loads (once per leg).
fm_scaled:
        ldy #$00
        lda (fmptr),y            ; byte 0 = scale (fraction of a semitone step /256)
        sta mul_a
        lda VSTEP_LO,x
        sta mul_m
        lda VSTEP_HI,x
        sta mul_m+1
        lda #$00
        sta mul_m+2
        sta mul_p
        sta mul_p+1
        sta mul_p+2
        ldy #$08
fm_mul:
        lsr mul_a
        bcc fm_mulskip
        lda mul_p
        clc
        adc mul_m
        sta mul_p
        lda mul_p+1
        adc mul_m+1
        sta mul_p+1
        lda mul_p+2
        adc mul_m+2
        sta mul_p+2
fm_mulskip:
        asl mul_m
        rol mul_m+1
        rol mul_m+2
        dey
        bne fm_mul
        lda mul_p                ; ROUND: (step*scale + $80) >> 8 — matches the
        clc                      ; ROM's vibrato depths exactly (47 @ step 362
        adc #$80                 ; needs rounding; truncation gives 46)
        sta mul_p
        lda mul_p+1
        adc #$00
        sta mul_p+1
        lda mul_p+2
        adc #$00
        sta mul_p+2
        ldy #$01                 ; product>>8 = mul_p+1/mul_p+2; hi bit0 = negative
        lda (fmptr),y
        and #$01
        beq fm_scpos
        sec                      ; negate (two's complement 16-bit)
        lda #$00
        sbc mul_p+1
        sta FM_OFF_LO,x
        lda #$00
        sbc mul_p+2
        sta FM_OFF_HI,x
        jmp fm_adv3
fm_scpos:
        lda mul_p+1
        sta FM_OFF_LO,x
        lda mul_p+2
        sta FM_OFF_HI,x
        jmp fm_adv3
; SLIDE setup (out-of-line for branch range; entered from the semitone-entry
; dispatch with A = speed). The MoN $FD portamento, trace-calibrated: speed 5 ->
; 112 Hz/frame, speed 6 -> 224 = 7 << (speed-1); ramps from the NEXT frame and
; fm_add clamps at FM_TGT. Rate sign follows the target direction (FM_ACC is 0
; on a fresh note, so sign(TGT) = the direction).
fm_slset:
        sta mul_a                ; speed
        lda #$07
        sta mul_m
        lda #$00
        sta mul_m+1
fm_slsh:
        dec mul_a
        beq fm_sldir
        asl mul_m                ; rate = 7 << (speed-1), 16-bit
        rol mul_m+1
        bmi fm_sldir             ; cap (huge speeds saturate; guard rejects those)
        jmp fm_slsh
fm_sldir:
        lda FM_TGT_HI,x
        bmi fm_slneg
        lda mul_m                ; slide up: OFF = +rate
        sta FM_OFF_LO,x
        lda mul_m+1
        sta FM_OFF_HI,x
        jmp fm_slon
fm_slneg:
        sec                      ; slide down: OFF = -rate
        lda #$00
        sbc mul_m
        sta FM_OFF_LO,x
        lda #$00
        sbc mul_m+1
        sta FM_OFF_HI,x
fm_slon:
        lda #$01
        sta FM_SLIDE,x
        jmp fm_adv3


.if DIGI_SPIKE
.include "digi_addrs.inc"
.endif
