"""
compare_filter_accuracy.py
==========================
Compare filter register accuracy between a SID ground-truth trace and
an SF2 conversion trace, both generated by zig64 sidm2-sid-trace.exe.

Usage:
    python compare_filter_accuracy.py [--sid CSV] [--sf2 CSV] [--verbose]

Outputs a per-frame comparison of the 4 SID filter registers:
  $D415 filter_freq_lo, $D416 filter_freq_hi,
  $D417 filter_res_control, $D418 filter_mode_volume
"""

import argparse
import csv
import os
import sys
from collections import defaultdict

FILTER_REGS = {
    'filter_freq_lo',
    'filter_freq_hi',
    'filter_res_control',
    'filter_mode_volume',
}

# zig64 trace format: mixed "--- Frame N ---" markers + CSV lines
def parse_trace(path: str) -> dict[int, dict[str, int]]:
    """
    Parse a zig64 trace file into {frame: {register: value}}.
    Tracks current value of each register across all frames.
    """
    state: dict[str, int] = {}          # current SID register state
    by_frame: dict[int, dict[str, int]] = {}  # snapshot per frame

    with open(path, encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    current_frame = None
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith('frame,cycle,register'):
            continue   # CSV header
        if line.startswith('---') or line.startswith('Loaded') or line.startswith('Mem') \
                or line.startswith('Calling') or line.startswith('INIT') \
                or line.startswith('Running') or line.startswith('[sid]'):
            continue   # preamble / frame markers (informational)
        # Try to parse as CSV: frame,cycle,register,old_val,new_val
        parts = line.split(',')
        if len(parts) < 5:
            continue
        try:
            frame = int(parts[0])
            reg   = parts[2].strip()
            # new_val is hex with $ prefix
            new_val_str = parts[4].strip().lstrip('$')
            new_val = int(new_val_str, 16)
        except (ValueError, IndexError):
            continue
        state[reg] = new_val
        if frame != current_frame:
            current_frame = frame
        # Store the updated filter state at this frame
        if reg in FILTER_REGS:
            if frame not in by_frame:
                by_frame[frame] = {}
            by_frame[frame][reg] = new_val

    # Fill in inherited state: build a complete per-frame register set
    # (a frame only appears if at least one filter reg changed that frame)
    return by_frame


def build_full_state(by_frame: dict, num_frames: int) -> list[dict]:
    """Expand per-frame deltas into full state per frame (inherited values)."""
    state = {r: 0 for r in FILTER_REGS}
    full = []
    for f in range(1, num_frames + 1):
        if f in by_frame:
            state.update(by_frame[f])
        full.append(dict(state))
    return full


def compare(sid_path: str, sf2_path: str, verbose: bool = False, sf2_offset: int = 0):
    print(f"\n=== Filter Accuracy: SF2 vs SID ground truth ===")
    print(f"  SID trace: {os.path.basename(sid_path)}")
    print(f"  SF2 trace: {os.path.basename(sf2_path)}")
    if sf2_offset:
        print(f"  SF2 frame offset: -{sf2_offset} (SF2 frame N maps to SID frame N+{sf2_offset})")

    sid_raw = parse_trace(sid_path)
    sf2_raw = parse_trace(sf2_path)

    num_frames = 300
    sid_full = build_full_state(sid_raw, num_frames)
    # Shift SF2 frame keys by +sf2_offset so that SF2 frame 0 aligns with SID frame 1.
    # build_full_state uses range(1, N+1) so without shifting, SF2 frame 0 is ignored.
    if sf2_offset:
        sf2_raw_shifted = {k + sf2_offset: v for k, v in sf2_raw.items()}
    else:
        sf2_raw_shifted = sf2_raw
    sf2_full = build_full_state(sf2_raw_shifted, num_frames)

    # Per-register stats
    reg_match  = {r: 0 for r in FILTER_REGS}
    reg_total  = {r: 0 for r in FILTER_REGS}
    mismatches = []   # (frame, reg, sid_val, sf2_val)

    for f in range(num_frames):
        frame = f + 1
        sid_s = sid_full[f]
        sf2_s = sf2_full[f]
        for reg in FILTER_REGS:
            sv = sid_s[reg]
            xv = sf2_s[reg]
            reg_total[reg] += 1
            if sv == xv:
                reg_match[reg] += 1
            else:
                mismatches.append((frame, reg, sv, xv))

    print(f"\n{'Register':<22}  {'Match':>6}  {'Total':>6}  {'Accuracy':>9}")
    print(f"  {'-'*22}  {'-'*6}  {'-'*6}  {'-'*9}")
    overall_match = overall_total = 0
    for reg in sorted(FILTER_REGS):
        m = reg_match[reg]
        t = reg_total[reg]
        pct = 100 * m / t if t else 0
        status = "OK" if pct >= 95 else ("WARN" if pct >= 50 else "FAIL")
        print(f"  {reg:<22}  {m:>6}  {t:>6}  {pct:>8.1f}%  {status}")
        overall_match += m
        overall_total += t

    overall_pct = 100 * overall_match / overall_total if overall_total else 0
    print(f"\n  {'OVERALL':<22}  {overall_match:>6}  {overall_total:>6}  {overall_pct:>8.1f}%")

    # Show first few mismatches
    if mismatches:
        print(f"\n  First mismatches ({min(20, len(mismatches))} of {len(mismatches)}):")
        print(f"  {'Frame':>6}  {'Register':<22}  {'SID':>6}  {'SF2':>6}")
        shown = set()
        for frame, reg, sv, xv in mismatches[:40]:
            key = (reg, sv, xv)
            if key not in shown or verbose:
                shown.add(key)
                print(f"  {frame:>6}  {reg:<22}  ${sv:02X}     ${xv:02X}")
                if len(shown) >= 20 and not verbose:
                    print(f"  ... (use --verbose for all)")
                    break

    # Summarise when filter activates in each trace
    sid_first = min((f+1 for f in range(num_frames)
                     if any(sid_full[f][r] != 0 for r in FILTER_REGS)), default=None)
    sf2_first = min((f+1 for f in range(num_frames)
                     if any(sf2_full[f][r] != 0 for r in FILTER_REGS)), default=None)
    print(f"\n  Filter first active — SID: frame {sid_first}, SF2: frame {sf2_first}")

    return overall_pct


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(script_dir)

    parser = argparse.ArgumentParser(description="Compare filter accuracy: SF2 vs SID")
    parser.add_argument('--sid', default=os.path.join(root, 'SID', 'stinsen_sid_trace_300frames.csv'))
    parser.add_argument('--sf2', default=os.path.join(root, 'SID', 'stinsen_laxity_fresh_trace.csv'))
    parser.add_argument('--verbose', action='store_true')
    parser.add_argument('--sf2-offset', type=int, default=1,
                        help='Frames SF2 is ahead of SID (default 1: SF2 frame 0 = SID frame 1)')
    args = parser.parse_args()

    for p in [args.sid, args.sf2]:
        if not os.path.isfile(p):
            print(f"ERROR: not found: {p}")
            sys.exit(1)

    pct = compare(args.sid, args.sf2, args.verbose, sf2_offset=args.sf2_offset)
    print(f"\n  FILTER ACCURACY: {pct:.1f}%\n")


if __name__ == '__main__':
    main()
