"""
Unit tests for Disassembler Integration Wrapper (sidm2/disasm_wrapper.py)

Tests Phase 2 enhancement - 6502 Disassembler integration into Step 8.5
"""

import unittest
import tempfile
from pathlib import Path
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from sidm2.disasm_wrapper import DisassemblerIntegration, disassemble_sid


class TestDisassemblerIntegration(unittest.TestCase):
    """Test DisassemblerIntegration class"""

    def setUp(self):
        """Set up test fixtures"""
        self.test_dir = Path(__file__).parent
        self.test_sid = self.test_dir.parent / 'Laxity' / 'Stinsens_Last_Night_of_89.sid'

    def test_disassembler_integration_available(self):
        """Test that disassembler integration is available"""
        from sidm2.disasm_wrapper import DisassemblerIntegration
        self.assertIsNotNone(DisassemblerIntegration)

    def test_read_sid_header(self):
        """Test reading SID file header"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        header = DisassemblerIntegration._read_sid_header(self.test_sid)

        self.assertIn('init_addr', header)
        self.assertIn('play_addr', header)
        self.assertIn('load_addr', header)
        self.assertIn('data_offset', header)

        # Verify addresses are reasonable
        self.assertGreater(header['init_addr'], 0)
        self.assertGreater(header['play_addr'], 0)

    def test_read_sid_data(self):
        """Test reading SID music data"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        data, load_addr = DisassemblerIntegration._read_sid_data(self.test_sid)

        self.assertIsNotNone(data)
        self.assertIsInstance(data, bytes)
        self.assertGreater(len(data), 0)
        self.assertGreater(load_addr, 0)

    def test_disassemble_sid_with_valid_file(self):
        """Test disassembling a valid SID file"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            self.assertIsNotNone(result)
            self.assertTrue(result['success'])
            self.assertTrue(result['init_file'].exists())
            self.assertTrue(result['play_file'].exists())
            self.assertGreater(result['init_lines'], 0)
            self.assertGreater(result['play_lines'], 0)
            self.assertGreater(result['init_size'], 0)
            self.assertGreater(result['play_size'], 0)

    def test_disassemble_sid_with_nonexistent_file(self):
        """Test disassembling a nonexistent SID file"""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=Path('nonexistent.sid'),
                output_dir=output_dir,
                verbose=0
            )

            self.assertIsNone(result)

    def test_disassembly_output_format(self):
        """Test that disassembly output has correct format"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            # Read init.asm
            with open(result['init_file'], 'r') as f:
                init_content = f.read()

            # Verify comment header
            self.assertIn("; Init Routine", init_content)
            self.assertIn("; Generated by SIDM2", init_content)
            self.assertIn("; Start:", init_content)
            self.assertIn("; Size:", init_content)

            # Verify assembly code format
            self.assertIn("$", init_content)  # Hex addresses
            self.assertTrue(
                any(mnem in init_content for mnem in ['LDA', 'LDX', 'LDY', 'STA', 'STX', 'STY', 'JMP', 'JSR', 'RTS'])
            )

    def test_convenience_function(self):
        """Test convenience function disassemble_sid()"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            self.assertIsNotNone(result)
            self.assertTrue(result['success'])

    def test_disassembly_returns_correct_data_types(self):
        """Test that disassembly result contains correct data types"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            self.assertIsInstance(result['success'], bool)
            self.assertIsInstance(result['init_file'], Path)
            self.assertIsInstance(result['play_file'], Path)
            self.assertIsInstance(result['init_addr'], int)
            self.assertIsInstance(result['play_addr'], int)
            self.assertIsInstance(result['init_size'], int)
            self.assertIsInstance(result['play_size'], int)
            self.assertIsInstance(result['init_lines'], int)
            self.assertIsInstance(result['play_lines'], int)

    def test_init_and_play_are_different(self):
        """Test that init and play disassemblies are different"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            # Init and play should typically have different addresses
            # (unless it's a very simple SID with shared routine)
            self.assertNotEqual(result['init_file'], result['play_file'])

            # Read both files
            with open(result['init_file'], 'r') as f:
                init_content = f.read()
            with open(result['play_file'], 'r') as f:
                play_content = f.read()

            # Content should be different
            self.assertNotEqual(init_content, play_content)

    def test_output_files_have_reasonable_size(self):
        """Test that output files are not empty and not unreasonably large"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            # Check file sizes
            init_size = result['init_file'].stat().st_size
            play_size = result['play_file'].stat().st_size

            # Files should be >100 bytes (header + some code)
            self.assertGreater(init_size, 100)
            self.assertGreater(play_size, 100)

            # Files should be <100KB (reasonable upper bound)
            self.assertLess(init_size, 100000)
            self.assertLess(play_size, 100000)

    def test_disassembly_includes_rts(self):
        """Test that disassembly includes RTS instruction"""
        if not self.test_sid.exists():
            self.skipTest(f"Test SID file not found: {self.test_sid}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)

            result = DisassemblerIntegration.disassemble_sid(
                sid_file=self.test_sid,
                output_dir=output_dir,
                verbose=0
            )

            # Read play.asm (should end with RTS)
            with open(result['play_file'], 'r') as f:
                play_content = f.read()

            # Should contain RTS instruction
            self.assertIn("RTS", play_content)


if __name__ == '__main__':
    unittest.main()
