"""Generated driver `.inc` files stay out of git.

Every native build rewrites `drivers_src/{mon,romuzak,blackbird}/*.inc` from the
rip it is building. They were tracked anyway, so `git status` was dirty after
any build, `git add -A` would commit one tune's tables over another's, and
`bin/_sm_build_all.py` carried a `git checkout --` to undo the damage after
every file it built.

Their tracked content was never canonical either: when all ten were regenerated
from absent, **four came back different** from what had been committed. What was
in git was whatever build last ran on whoever's machine committed it.

`drivers_src/galway/*.inc` had been ignored for exactly this reason since long
before; the other three families were simply never given the same treatment.
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GENERATED_INC_DIRS = ("mon", "romuzak", "blackbird", "galway")


def _tracked_files():
    out = subprocess.run(["git", "ls-files", "drivers_src"], cwd=ROOT,
                         capture_output=True, text=True)
    return [l.strip().replace("\\", "/") for l in out.stdout.splitlines() if l.strip()]


def test_no_generated_inc_is_tracked():
    """A tracked .inc under a generated driver dir means builds dirty the tree."""
    bad = [f for f in _tracked_files()
           if f.endswith(".inc")
           and f.split("/")[1] in GENERATED_INC_DIRS]
    assert not bad, (
        "these .inc files are regenerated by every build and must not be tracked "
        "(git rm --cached + .gitignore): " + ", ".join(bad))


def test_gitignore_covers_every_generated_driver_dir():
    """Untracking alone is not enough — without the ignore rule the next
    `git add -A` after a build silently re-adds them."""
    ign = open(os.path.join(ROOT, ".gitignore"), encoding="utf-8").read()
    for d in GENERATED_INC_DIRS:
        assert f"drivers_src/{d}/*.inc" in ign, (
            f"drivers_src/{d}/*.inc is not in .gitignore, so a build's output "
            f"can be committed by accident")


def test_no_script_restores_the_inc_files_any_more():
    """Restoring the .inc files after a build is now dead code, and leaving it
    in would `git checkout` a path that is no longer in the index.

    Scans whatever build scripts exist rather than naming one: `bin/_*.py` is
    itself gitignored, so the script that carried this workaround
    (`_sm_build_all.py`) is absent from a fresh clone and cannot be asserted on
    directly.
    """
    import glob
    for path in glob.glob(os.path.join(ROOT, "bin", "*.py")):
        src = open(path, encoding="utf-8", errors="ignore").read()
        for d in GENERATED_INC_DIRS:
            assert f'"drivers_src/{d}/layout.inc"' not in src, (
                f"{os.path.basename(path)} still git-checkouts a generated .inc; "
                f"that path is no longer tracked")
